### ISSUE TITLE
Wrong Action for CTRL + ALT + DELETE

### ISSUE THREAD

**Issue by willysr** [mate-desktop/mate-control-center#107]
CTRL + ALT + DELETE is supposed to be used for logout process, but what's executed is a shutown/reboot

Also, changing the logout key to another key does not affect anything. It will show the shutdown dialog as well.

OS: Slackware 14.1 (current)

**Comment by monsta** [comment]
This discussion went nowhere and https://github.com/mate-desktop/mate-settings-daemon/pull/76 actually does another thing, so I guess this issue can be closed...

**Comment by NiceandGently** [comment]
For me CTRL + ALT + DELETE is always reboot !
Can be closed.
