### ISSUE TITLE
appearance-properties: Desktop theme does not show up when IconTheme is not in index.theme

### ISSUE THREAD

**Issue by infirit** [mate-desktop/mate-control-center#110]
So we had some users on irc that had problems with the Numix theme [1] not showing up in the appearance-properties. It looks like it expects a IconTheme entry under [X-GNOME-Metatheme] which the Numix index.theme file does not have.

At the moment it is confirmed failing on Mint 17, Arch and Gentoo (build from git).

[1] http://satya164.deviantart.com/art/Numix-GTK3-theme-360223962
##

**Comment by raveit65** [comment]
fixed in numix
https://github.com/numixproject/numix-gtk-theme/issues/488
