### ISSUE TITLE
keybinding: key binding using 'Win' key(Mod4) is not always triggered if 'Win' key is not pressed in advance..

### ISSUE THREAD

**Issue by adam900710** [mate-desktop/mate-control-center#115]
I binded 'win+e' key for 'Home folder' action in mate-keybinding-properties.

However the 'win+e' seems not always triggered, sometimes I need to press 'Win+e' twice to correct launch caja.

On the other hand, when using pure openbox(without LXDE or other DE), after binding 'Win+e' for caja, the shortcut is never missed.

After several tries, I find if I press Win key for about 0.2 second or longer and then press 'e' key, caja can always be trigger.
But if I keep the habit of using openbox, which I press win key just a little eariler (maybe 0.1 second?) than 'e' key, the binded action will be much harder to execute.

Can mate handle 'Win'(Mod4) key in a faster way?
Thanks.
##

**Comment by monsta** [comment]
@flexiondotorg: I guess it had been fixed for some time now? I can't reproduce it with or without https://github.com/mate-desktop/mate-settings-daemon/pull/179.

**Comment by monsta** [comment]
Closing as there's no response and it's not a control center issue anyway
