### ISSUE TITLE
Gtk3: appearance properties: theme preview glitches

### ISSUE THREAD

**Issue by monsta** [mate-desktop/mate-control-center#137]
VirtualBox, Debian Testing, GTK+3 build of MATE 1.9 (all packages are from git master), GTK+ 3.14.5.

![1](https://cloud.githubusercontent.com/assets/5138986/5568733/953707ac-8f73-11e4-9c48-f5a053ae32a2.png)
![2](https://cloud.githubusercontent.com/assets/5138986/5568734/9872ff70-8f73-11e4-821b-19fb18a8c200.png)

The thumbnails that are displayed ok are supposedly the leftovers from GTK+2 build of MATE that was installed here previously. If I delete (or move) ```~/.cache/thumbnails``` dir, more thumbs will have the glitches:

![3](https://cloud.githubusercontent.com/assets/5138986/5568776/36ea6364-8f74-11e4-85d9-85b6611aa651.png)

**Comment by dnk** [comment]
would be fixed by https://github.com/mate-desktop/mate-control-center/pull/201

**Comment by willysr** [comment]
Now everything is "?"
![appearance](https://cloud.githubusercontent.com/assets/240100/11762064/4b5fe058-a10c-11e5-8c9d-22902980941d.jpg)
