### ISSUE TITLE
 Hotkeys in the right-click menu 

### ISSUE THREAD

**Issue by tranjeeshan** [mate-desktop/mate-control-center#141]
Ubuntu MATE can implement hotkeys in the right-click mneus. For example, Right click on a file and press 'R' to rename it. The hotkeys could be underlined; like underlined R in 'Rename'.

**Comment by NiceandGently** [comment]
which menus do you mean?
I quess this disable in your theme.
see https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-2.0/gtkrc#L26
gtk-auto-mnemonics = 1
With that setting and pressing 'ALT' you will see the hotkeys in menus.

**Comment by monsta** [comment]
How is that related to m-c-c?

**Comment by NiceandGently** [comment]
@monsta 
this is not related to m-c-c and is simply a theme setting.
I don't see that this is a valid report,,,,,,and no answer from reporter.

**Comment by monsta** [comment]
@flexiondotorg: looks like it can be closed then.
