### ISSUE TITLE
Unable to see font characters while using mate-font-viewer

### ISSUE THREAD

**Issue by shirishag75** [mate-desktop/mate-control-center#143]
Dear Developer, 
Thank you for making mate desktop and mate-control-center.  

The issue at hand is I was trying to see a font file but am getting empty rectangular boxes while the same font is seen in all it's glory while viewing the same via gnome-font-viewer. 

Sharing how it looks under mate-font-viewer and gnome-font-viewer. 

![mate-font-viewer](https://cloud.githubusercontent.com/assets/727626/6101561/1c64d440-b04c-11e4-88f4-1a030563aa3a.png)

![gnome-font-viewer](https://cloud.githubusercontent.com/assets/727626/6101563/25104f5c-b04c-11e4-9972-68ac529d554e.png)

Look forward to a solution.
##

**Comment by monsta** [comment]
I confirm that - but only with this particular font. Other fonts like Droid or Noto are displayed properly.

**Comment by NiceandGently** [comment]
After i read those commit https://git.gnome.org/browse/gnome-font-viewer/commit/?id=d11b6ae9f8e1a62fe366e349793a38e7040aefb5
i think this lines in code needs to be adjusted.
https://github.com/mate-desktop/mate-control-center/blob/master/font-viewer/font-thumbnailer.c#L319

**Comment by monsta** [comment]
It can't be applied... it's another part of code from another file (which we apparently don't have here).

**Comment by infirit** [comment]
The function ``check_font_contains_text`` is in ``font-view.c`` and the only change compared to MATE is the calling FT_Select_Charmap. Below is an untested patch for this commit.

Where can I download this font? ``android emoji`` does not seam to be something I can install here.. 

```diff
diff --git a/font-viewer/font-view.c b/font-viewer/font-view.c
index cf3c651..eb1c1e3 100644
--- a/font-viewer/font-view.c
+++ b/font-viewer/font-view.c
@@ -61,6 +61,8 @@ draw_string (cairo_t *cr,
 static gboolean
 check_font_contain_text (FT_Face face, const gchar *text)
 {
+    FT_Select_Charmap (face, FT_ENCODING_UNICODE);
+
     while (text && *text) {
 	    gunichar wc = g_utf8_get_char (text);
```

**Comment by NiceandGently** [comment]
@infirit 
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/Bugs/android-emoji.ttf

**Comment by infirit** [comment]
patch does not work, ignore it.

**Comment by NiceandGently** [comment]
I've this working with gtk3.
![bildschirmfoto-android-emoji-regular](https://cloud.githubusercontent.com/assets/961604/9428017/f21ef7ae-499a-11e5-84a7-10a65dfde3a9.png)
I backport those commits (port to SushiFontloader), but this breaks any compatibility gtk2.
https://git.gnome.org/browse/gnome-font-viewer/commit/?id=f50e4c4
https://git.gnome.org/browse/gnome-font-viewer/commit/?id=9e30877
https://git.gnome.org/browse/gnome-font-viewer/commit/?id=79a3e86
