### ISSUE TITLE
 MATE: keyboard shortcuts missing in mate-keybinding-properties

### ISSUE THREAD

**Issue by posophe** [mate-desktop/mate-control-center#146]
From https://bugzilla.opensuse.org/show_bug.cgi?id=920671
"In the MATE keyboard shortcuts dialog, there are only a few entries for the music bindings and for general applications, no Window Manager actions, nothing else. So it seems like something is very broken.

In addition, shortcuts involving META key (windows key) don't work. I tried setting Win-E to caja, but nothing happens. Not sure if this is just a related problem. (also see maybe related bug 792682 (https://bugzilla.opensuse.org/show_bug.cgi?id=792682) - X11:MATE: Terminal keyboard shortcut doesn't work)"

**Comment by monsta** [comment]
Seems like a distro-specific issue - I can't reproduce it in Debian and Ubuntu.

**Comment by NiceandGently** [comment]
Same for fedora, all keyboard shortcuts are there.

**Comment by monsta** [comment]
@posophe: does it still happen in 1.10?

**Comment by monsta** [comment]
Looks like it doesn't... :smile:

**Comment by posophe** [comment]
I asked for more infos from the reporter, so I guess so

**Comment by morsik** [comment]
I just installed Mate on Fedora 23. I don't see "Window Shortcuts". Maybe this needs some specific package installed I don't have?

PS I'm using Compiz with Emerald decorator.

**Comment by raveit65** [comment]
> PS I'm using Compiz with Emerald decorator.
Of course the keybindings are in ccsm under general.

**Comment by smithtim** [comment]
I am having the same issue in MATE 1.20.4 on NixOS 18.09.  Under Keyboard Shortcuts, the only two categories are "Sound" and "Desktop".  I do not see "Window Management", "Accessibility", or any other categories.

**Comment by monsta** [comment]
That's probably fixed by https://github.com/mate-desktop/mate-control-center/pull/434.

**Comment by smithtim** [comment]
Confirmed that this is fixed for me in MATE 1.22.1 on NixOS 19.09.
