### ISSUE TITLE
Have seperate sensitivity and acceleration settings for mouse and trackpad

### ISSUE THREAD

**Issue by joelewing** [mate-desktop/mate-control-center#148]
On my laptop, I have found that the sensitivity and acceleration settings need to be different with my mouse versus my trackpad for the best user experience.  Is there some way where there could be seperate settings for mouse (or even settings for multiple different mice) and trackpad?
##

**Comment by monsta** [comment]
It had been added in 1.18 via https://github.com/mate-desktop/mate-control-center/pull/258.
