### ISSUE TITLE
mate-display-properties will crash when you change the resolution and then click "apply"

### ISSUE THREAD

**Issue by HuangZhiquan** [mate-desktop/mate-control-center#149]
Will you not fix the bug?

**Comment by NiceandGently** [comment]
It is fixed already by gtk2, you need to install gtk2-24.17.
see https://github.com/mate-desktop/mate-control-center/issues/86

marked as can be closed

**Comment by HuangZhiquan** [comment]
i have installed 2.24.25,but the bug exists yet.2.24.17 will make mate-control-center "debuild" being failed

**Comment by NiceandGently** [comment]
opps, sorry, typo.
you need gtk2-2.24.26 or gtk2-2.24.27, better .27

**Comment by NiceandGently** [comment]
@HuangZhiquan 
any news with gtk2-2.24.26 or gtk2-2.24.27 ?

**Comment by HuangZhiquan** [comment]
i am so sorry that i forgot to reply, yes, it works very well with gtk2-2.24.27
