### ISSUE TITLE
libslab: actions_section items do not get translated on non-English desktops

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-control-center#151]
Hi,

the "Common Tasks" section ("Häufige Aufgaben" in German) contains task names that are still English, though m-c-c is running on a German localized desktop.

It looks like this needs to be adapted in

  libslib/app-shell.c

somewhere.

Greets,
Mike

**Comment by NiceandGently** [comment]
@sunweaver 
The fix is to change
```
#: ../org.mate.control-center.gschema.xml.in.in.h:1
msgid ""
"[ 'Change Theme;mate-appearance-properties.desktop', 'Set Preferred "
"Applications;mate-default-applications-properties.desktop' ]"
msgstr "[ »Thema ändern;mate-appearance-properties.desktop«, »Bevorzugte Anwendungen einstellen;mate-default-applications-properties.desktop« ]"
```
to
```
#: ../org.mate.control-center.gschema.xml.in.in.h:1
msgid ""
"[ 'Change Theme;mate-appearance-properties.desktop', 'Set Preferred "
"Applications;mate-default-applications-properties.desktop' ]"
msgstr "[ 'Thema ändern;mate-appearance-properties.desktop', 'Bevorzugte Anwendungen einstellen;mate-default-applications-properties.desktop' ]"
```
But transiflex gives me always a error if i try to change that.
Please register to transiflex and try to change it, maybe you're more lucky than me.

**Comment by NiceandGently** [comment]
@monsta 
yes, this fixed

**Comment by sunweaver** [comment]
@NiceAndGently: in transifex? Or in MATE upstream?

**Comment by NiceandGently** [comment]
@sunweaver 
at transiflex, as project manager you should see it there

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/mate-control-center/commit/fabdd922e42180f45b02407bdd88a73b2c166b9f.
