### ISSUE TITLE
missing adjustments for glib2-2.43

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-control-center#155]
for example changing keybindings  for 'windows managment' applies only after a session restart.
Not shure if this isn't marco releated.

**Comment by NiceandGently** [comment]
Further investigations shows that the issue only exists wit WM keybindings.
A change of desktop and sound keybindings works well.

**Comment by NiceandGently** [comment]
@monsta 
all windows-kebinding are working now with your fix :)
thank you.

**Comment by NiceandGently** [comment]
https://github.com/mate-desktop/marco/pull/187

**Comment by monsta** [comment]
That PR only fixes workspace names notifications.
Fixes for keybindings are in https://github.com/mate-desktop/marco/pull/189 and https://github.com/mate-desktop/marco/pull/190.

@stefano-k: please merge them all, they're all important.

**Comment by monsta** [comment]
With all these PRs merged, this issue can be closed I guess.
