### ISSUE TITLE
[fixed] Mate default applications program

### ISSUE THREAD

**Issue by lahtis** [mate-desktop/mate-control-center#156]
When im adding programs MATE a the default applications program.

Internet tab. WWW-browser
im adding default browser to Midori.
When im using example a use Gulf program and select a help. -> documentation.
It is open Firefox program. Firefox not a default program. This is a bug.

im using 14.10 Ubuntu MATE
Mate is 1.8.2

**Comment by lahtis** [comment]
it is fixed.

**Comment by monsta** [comment]
@stefano-k: can be closed then
