### ISSUE TITLE
background slide show timing no longer correct with respect to system time zone and background file's start time

### ISSUE THREAD

**Issue by AprilVRose** [mate-desktop/mate-control-center#159]
Wolfgang Ulbrich advised me to report this issue against mate-control-center. Can you confirm whether mate-control-center is the software which controls the timing of background slide shows?

Starting in Fedora 22, the Mate software which controls background slide show timing no longer properly adjusts for the system time zone, nor for the start time specified in the background slide show's XML file. This is relevant for slide shows which display certain content based upon the time of day.

In my case, I am using the Fedora Infinity background. The Fedora Infinity background has 4 images which transition depending upon the time of day ... sunrise (green), day (blue), sunset (pink), and night (dark purple) ... in my time zone (Eastern Daylight (UTC-04:00)), the timing is offset by 11 hours because of the combination of the time zone difference and the fact that the background XML file specifies a start time of 07:00 (4+7=11).

I was able to determine that the start time specified in the background's XML file (/usr/share/backgrounds/infinity/infinity.xml) is not recognized by changing its value and observing that this had no effect.

I was able to confirm the time zone issue by changing to London time and observing a corresponding reduction in the offset.

Wolfgang Ulbrich suspects that the issue may be with a change in how UTC time is controlled by an underlying system component, perhaps systemd.

Steps to reproduce:
1) switch system time zone to America/New York
2) install fedorainfinity-backgrounds
3) open Appearance Preferences, navigate to "Background" tab, select "Add", switch to show "All files", navigate to /usr/share/backgrounds/infinity, and then select the XML file.

To get the clearest results, the best times to test this are ...

 - between 7:00 a.m. (07:00) and 8:00 a.m. (08:00) -- correct color for this period is green
 - between 1:00 p.m. (13:00) and 3:00 p.m. (15:00) -- correct color for this period is blue
 - between 6:00 p.m. (18:00) and 7:00 p.m. (19:00) -- correct color for this period is pink
 - between 12:00 a.m. (00:00) and 5:00 a.m. (05:00) -- correct color for this period is dark purple

Any period outside of these ranges is a blend of two colors and so is more ambiguous.

Note that if you continue to experiment with different times or time zones, you will need to take certain steps to see how this affects the Fedora Infinity background timing. After adjusting the time, you will need to:
1) change to a background other than Fedora Infinity and close out of Appearance Preferences
2) re-open Appearance Preferences and set Fedora Infinity as the background.

**Comment by NiceandGently** [comment]
@AprilVRose 
Hi,
i am Wolfgang.
Thanks for openning the report here.

**Comment by NiceandGently** [comment]
mate-appearance-properties is the failed application and it's part or mate-control-center.

**Comment by monsta** [comment]
I confirm this issue in my LMDE (Linux Mint Debian Edition) 2 "Betsy", based on Debian Jessie.

I see it with a different slideshow though - "Cosmos" from ```mate-screensaver-common``` package.

**Comment by NiceandGently** [comment]
I can confirm that both background suites, fedora infinty and our cosmic, are working well in fedora 21, but not in fedora 22 anymore.

**Comment by NiceandGently** [comment]
@AprilVRose 
As a workaround, did you tried to change the background images in xml file?

**Comment by AprilVRose** [comment]
I'm quite sure that would work, but the modifications to the XML file would apply only to me. Each user would have to apply and maintain their own unique modifications to get slide shows to work correctly.

**Comment by NiceandGently** [comment]
Shure, this is only a suggestion to help you for the momment.
The problem is not so trivial because we have diiferent results in different distros, with or without systemd.
And it seems that the problem exists also with mate-1.8 in other distros.
It looks like that fedora 21 was the only distro where is had worked.

**Comment by AprilVRose** [comment]
To clarify, I've been using Fedora Infinity since Fedora 8, just so it's clear that this didn't only work in that one version of Fedora.

I will be happy to test old versions of other distros. Just let me know what will be helpful for me to test.

I presume you're trying to narrow down what underlying software change resulted in the break. Might it be any easier to look at the code which controls the background slide shows to see where it's getting the time information from?

**Comment by NiceandGently** [comment]
Ok, it's definitive a regression.
I updated local rhel7/centos7 repo to 1.10 yesterday which use day/night fading backgounds, and the background switch from night to day in the middle of the night.
Which is bad because it's the default background in rhel7 or centos7.
So we need to find out which application is responsable setting the time.

**Comment by AprilVRose** [comment]
In Fedora 21, the regression is in one or both of the following packages:
mate-desktop
mate-desktop-libs

Updating all packages but the two listed above using the following command does not result in the regression (but note that it does result in a broken mate desktop, so don't try on your primary box!):
dnf --exclude=mate-desktop --exclude=mate-desktop-libs update

On the other hand, updating all packages (including the two listed above) does result in the regression. This confirms that the regression exists in one of both of the named packages.

**Comment by NiceandGently** [comment]
@AprilVRose 
I can build a rpm for testing, what fedora version do you prefer? f21/f22  x86_64/i686
In centos7 i could fix the issue with that revert.

**Comment by AprilVRose** [comment]
Fedora 22 x86_64 :-)

**Comment by NiceandGently** [comment]
@AprilVRose 
here we go
https://dl.dropboxusercontent.com/u/49862637/Mate-desktop/SOURCE/mate-desktop.tar.xz
If this fixes the issue with your Infinity background simply close this issue.
Than i will rebuild mate-desktop for fedora.

**Comment by AprilVRose** [comment]
Tried to install mate-desktop-1.10.1-2.fc22.x86_64.rpm and mate-desktop-libs-1.10.1-2.fc22.x86_64.rpm, but here's the result:

Package mate-desktop-1.10.1-2.fc22.x86_64 is already installed, skipping.
Package mate-desktop-libs-1.10.1-2.fc22.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by AprilVRose** [comment]
Downgraded and then installed the provided rpm files ... these packages appear to fix the issue -- thanks! :-)
