### ISSUE TITLE
checkbox for reverse scrolling

### ISSUE THREAD

**Issue by artgtan** [mate-desktop/mate-control-center#162]
I'm using Ubuntu MATE 14.04 with the MATE 1.82 desktop.

Under System - Preferences - Mouse, there is no checkbox to toggle reverse (natural) scrolling. 

Can something like this be added in the future?

**Comment by conorew** [comment]
I'd like this also

**Comment by dnk** [comment]
implemented at https://github.com/mate-desktop/mate-control-center/commit/e4c68641268956ff99cef21dc5e5cb3e3b55ccdf

**Comment by conorew** [comment]
Fantastic, I shall update my is!

Thank you!

**Comment by artgtan** [comment]
Thank you!
