### ISSUE TITLE
GTK3: Keyboard layout is invisible

### ISSUE THREAD

**Issue by City-busz** [mate-desktop/mate-control-center#169]
In Keyboard Preferences > Layouts > Show... > Keyboard Layout:
The keyboard layout is rendered, but has no height, therefore not visible on GTK3.

**Comment by infirit** [comment]
Which version are you running as it should be fixed in 1.10.1 (commit 1b26e9e71915162cfe4903abad1b74f193c4f328).

**Comment by City-busz** [comment]
I'm using the following package versions on Arch Linux:
- mate-control-center 1.10.1
- gtk3 3.16.6

**Comment by NiceandGently** [comment]
i guess this is needed https://github.com/mate-desktop/libmatekbd/commit/55a4c5de95341a98f39b372beea40a4763296e1e

**Comment by City-busz** [comment]
Yes, it fixes the problem. Thanks!
