### ISSUE TITLE
GTK3: mate-appearance-properties, colour change problem

### ISSUE THREAD

**Issue by black77** [mate-desktop/mate-control-center#170]
Changing window background colour doesn’t affect all apps. In openSUSE that doesn’t affect Authentication window, its colour remains to be default. That also confirmed for some Ubuntu apps in forum.
![theme](https://cloud.githubusercontent.com/assets/364128/9021175/b9722b92-383d-11e5-9010-58cbf32e2015.png)
##

**Comment by NiceandGently** [comment]
I think failed applications are gtk3 ?

**Comment by black77** [comment]
libgnomesu package is responsible for the window, I checked it dependencies and it looks like yes gtk3

**Comment by monsta** [comment]
Hmm... but shouldn't m-a-p change the settings for both GTK's?

**Comment by NiceandGently** [comment]
With m-a-p gtk3 version this is complete broken, which shows me that the code can't set gtk3 apps.

**Comment by raveit65** [comment]
I noticed that m-a-p (gtk3) can change color of gtk2 applications.

**Comment by DavidGriffith** [comment]
Has someone submitted a bug report to https://bugzilla.gnome.org/ about this?  If so, I don't see any obvious subjects.

**Comment by raveit65** [comment]
Dropped for gtk+-3

**Comment by DavidGriffith** [comment]
What do you mean "dropped"?  It still appears that GTK3 is supposed to support it, but it doesn't.  That's sounds like an upstream bug to me.  I'm trying to figure out if anyone has talked to the Gnome people about it.

**Comment by raveit65** [comment]
Dropped mean, it is impossible to do that as gtk3 theming is to much complex for a simple gui like it was.

**Comment by DavidGriffith** [comment]
What needs to happen for this functionality to be restored?

**Comment by DavidGriffith** [comment]
FWIW, here's my report to the Gnome people:  https://bugzilla.gnome.org/show_bug.cgi?id=780527

**Comment by cwendling** [comment]
Altering themes, and especially GTK3 ones is a very challenging task.  For now, the best solution and tool I could find is https://github.com/actionless/oomox/, which allows to generate customized themes.
