### ISSUE TITLE
Compilation error: mate-settings-daemon include not found

### ISSUE THREAD

**Issue by brunodefraine** [mate-desktop/mate-control-center#171]
I was compiling mate-desktop (for a prefix other than /usr) and got a compile error for the following file from mate-control-center:

    capplets/common/activate-settings-daemon.c

The following include cannot be resolved:

    #include <mate-settings-daemon/mate-settings-client.h>

The compilation is configured using the pkg-config file from mate-settings-daemon, but this already includes the subdirectory "mate-settings-daemon" in the include path given in cflags:

https://github.com/mate-desktop/mate-settings-daemon/blob/master/data/mate-settings-daemon.pc.in

So either you should include without the subdir:

    #include <mate-settings-client.h>

Or the pkg-config file for mate-settings-daemon should not include the subdir:

    Cflags: -I${includedir}

**Comment by brunodefraine** [comment]
I was compiling mate-desktop (for a prefix other than /usr) and got a compile error for the following file from mate-control-center:

    capplets/common/activate-settings-daemon.c

The following include cannot be resolved:

    #include <mate-settings-daemon/mate-settings-client.h>

The compilation is configured using the pkg-config file from mate-settings-daemon, but this already includes the subdirectory "mate-settings-daemon" in the include path given in cflags:

https://github.com/mate-desktop/mate-settings-daemon/blob/master/data/mate-settings-daemon.pc.in

So either you should include without the subdir:

    #include <mate-settings-client.h>

Or the pkg-config file for mate-settings-daemon should not include the subdir:

    Cflags: -I${includedir}

**Comment by infirit** [comment]
Did you install mate-settings-daemon in the same prefix? If not then that is the source of your problem.

**Comment by brunodefraine** [comment]
Yes, I did.

The source of the problem is that either the include statement or the include-dir cflag should specify the "mate-settings-daemon" subdir, but not both.

If I remove the "mate-settings-daemon" subdir in either place, I can compile just fine.

**Comment by infirit** [comment]
I see now. Fixed in 6bc0f4e76eaf22758002af90bac5ecbdc4ade742
