### ISSUE TITLE
Wish: mate-volume-control to allow moving applications between soundcards

### ISSUE THREAD

**Issue by RichardNeill** [mate-desktop/mate-control-center#173]
Some mixers allow the user to choose which sound stream goes to which sound card (and to move them around in realtime). pavucontrol does this, as does the standard KDE mixer, but the mate-volume-control doesn't.  Here's why it's useful for me (and many others who have at least one extra source of sound).

I have 2 soundcards, one of which connects to my monitor's internal 0.5W speaker, while the other connects to my hi-fi.  The latter is usually left on and moderately loud (because Classical music in particular has a large dynamic range).

So, when I play my music, or youtube, I want to hear the sound through the hi-fi. But for system bongs, startup sounds, terminal beeps, and all sorts of unexpected sounds that arise from web-pages, I really don't want to hear them fortissimo! 

The easiest way to try this out is to launch pavucontrol and experiment with it - then either (a) copy this functionality into Mate-volume-control, or (b) in the meantime, add a link/explanation in mate-volume-control that launches pavucontrol.  Thanks for your time.

**Comment by raveit65** [comment]
Thanks for reporting this, but mate-volume-control is part of mate-media.
Sorry we can't move reports here at github.
Can you please open a new one there?

**Comment by monsta** [comment]
@mratajsky: how do you think, is it possible to do? If yes, I'll open a new feature request in mate-media or libmatemixer, depending on where it could be implemented.

**Comment by RichardNeill** [comment]
It's already done in pavucontrol, so I think you could borrow some 
source code from there... HTH - Richard

**Comment by mratajsky** [comment]
Yes it is possible and IIRC libmatemixer can do this already, we'll just need the GUI in mate-media.

**Comment by monsta** [comment]
Ok, I opened https://github.com/mate-desktop/mate-media/issues/74 and closing this one.
