### ISSUE TITLE
crtl+alt-backspace for killing x-server applies only after a session restart 

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-control-center#178]
Possible GLib >= 2.43 'first connect to settings, then read them' issue.
Im not really shure that m-c-c is the right package for this issue.

@leigh123linux

**Comment by leigh123linux** [comment]
Is this the code responsible for it?

https://github.com/mate-desktop/mate-control-center/blob/master/capplets/keyboard/mate-keyboard-properties-xkbot.c#L508

**Comment by monsta** [comment]
Ok so it's ```'terminate\tterminate:ctrl_alt_bksp'``` value in ```options``` key in ```org.mate.peripherals-keyboard-xkb.kbd``` schema...
It seems to be the work of https://github.com/mate-desktop/mate-settings-daemon/issues/105 again...
