### ISSUE TITLE
mate-display-properties segfault

### ISSUE THREAD

**Issue by rvillablanca** [mate-desktop/mate-control-center#179]
When I launch mate-display-properties, I receive a segmentation fault.

I'm using Debian Sid/Unstable stretch, with Mate version 1.10.1. 
Linux debian 4.1.0-1-amd64 # 1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 GNU/Linux.
With this bug, it is impossible to configure dual monitor.

I don't know how to view debug message to provide more information about the error.
![screenshot](https://cloud.githubusercontent.com/assets/1508272/9225399/8a96bfea-40df-11e5-9ea4-5e47651512e6.png)

**Comment by flexiondotorg** [comment]
Not all the MATE 1.10 packages have made it to Debian unstable yet. I'll close this now but please reopen if the problem persists when the MATE 1.10 transition is complete.

**Comment by yasbean** [comment]
Is the transition complete, yet?  Because I, too, am getting a segmentation fault when trying to launch.  Same system, same kernel.
