### ISSUE TITLE
Mate display properties crash after upgrade mate-desktop to version 1.10.1-1 in Debian 8

### ISSUE THREAD

**Issue by ledzgio** [mate-desktop/mate-control-center#180]
Yesterday I have upgraded from repo and there was an update regarding mate-desktop and mate-desktop-common to version 1.10.1 (while the rest of the packages are 1.8.x). Well I upgraded and now I cannot start mate-display-properies to configure my monitor, it crashes all the time. This is the error found with gdb:
Starting program: /usr/bin/mate-display-properties 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".
[New Thread 0xb645ab40 (LWP 5958)]
Program received signal SIGSEGV, Segmentation fault.
0x0804df51 in _start ()
(gdb) backtrace full
#0  0x0804df51 in _start ()
No symbol table info available.

I am on Debian 8 testing
Linux debian 4.1.0-1-686-pae #1 SMP Debian 4.1.3-1 (2015-08-03) i686 GNU/Linux

Any idea?

thanks

**Comment by monsta** [comment]
Debian 8.0 is the current stable release and you're using the future 9.0 release (as it's testing repo).

There was an API change during 1.10 development (https://github.com/mate-desktop/mate-control-center/commit/e9bf4efa713959e68d61db7fbca93f7dfea2ae5e and some other commits), I think that's what causes m-c-c 1.8 to fail with mate-desktop 1.10.

In other words, it's not upstream issue, it's a Debian issue. See [this comment](https://bugs.debian.org/795171#15) from one of MATE Debian maintainers.
