### ISSUE TITLE
ORCA and accessibility tools no more disponibles

### ISSUE THREAD

**Issue by Petrouchka** [mate-desktop/mate-control-center#183]
Jean-Philippe MENGUAL ( contact@hypra.fr or texou@accelibreinfo.eu ) and other peopleadded ORCA and other soft for accessibility to MATE but only in Debian. Should contact them to ask if they can add ORCA to MATE for Mint.
![capture-applications preferees](https://cloud.githubusercontent.com/assets/3955499/9411215/01ddd164-4825-11e5-85da-5b16e1e11d43.png)

**Comment by monsta** [comment]
Mint-specific issues should be reported to Mint bug tracker at Launchpad, not here.

**Comment by Petrouchka** [comment]
In launchpad https://launchpad.net/linuxmint or in Git https://github.com/linuxmint ?
I'm lost.

**Comment by infirit** [comment]
In launchpad https://launchpad.net/linuxmint
