### ISSUE TITLE
[Patch] Add Comment for desktop file

### ISSUE THREAD

**Issue by glixx** [mate-desktop/mate-control-center#187]
``` diff
diff -ur mate-control-center.orig/shell/matecc.desktop.in.in mate-control-center/shell/matecc.desktop.in.in
--- mate-control-center.orig/shell/matecc.desktop.in.in 2015-08-28 16:52:28.000000000 +0300
+++ mate-control-center/shell/matecc.desktop.in.in  2015-08-28 17:02:07.000000000 +0300
@@ -1,6 +1,7 @@
 [Desktop Entry]
 _Name=Control Center
 _GenericName=The MATE configuration tool
+_Comment=The Control Center for MATE
 Icon=preferences-desktop
 Exec=mate-control-center
 Terminal=false
```
##

**Comment by monsta** [comment]
Please use pull requests for submitting patches...

**Comment by glixx** [comment]
http://wiki.mate-desktop.org/contribute#send_a_patch
"The best way to propose a patch is to send it with a pull request."
Pull requests are not mandatory, it's only "the best way". Issues works too.

**Comment by monsta** [comment]
I've made the comment a verb, like it's done in our other apps: https://github.com/mate-desktop/mate-control-center/commit/55c35caad2779d55bb37b98775b9b63e25b294e1
