### ISSUE TITLE
mate-display-properties: unexpected behaviour

### ISSUE THREAD

**Issue by stenad4711** [mate-desktop/mate-control-center#198]
The GUI always belevies the physical width or height of a display are the same regardless of user selected rotation. If you have more than one display and rotate them left or right you cannot place them logically edge to edge in the GUI since it beleives it will overlap.  I manually edited the monitors.xml to fix this. Perhaps the GUI should have borth physical properties (HW layer) and logical properties, so it doesent get confused.
##

**Comment by llbit** [comment]
Here is a screenshot illustrating this issue:

![cyhnlq5wqaatq82](https://cloud.githubusercontent.com/assets/2757386/13423262/0e7246dc-df9a-11e5-9037-e4936c00899b.png)

I hope it gets fixed soon. Where is the monitors.xml file by the way?

**Comment by stenad4711** [comment]
In your home directory:
~/.config/monitors.xml

There is also one at /etc/mate-settings-daemon/xrandr/monitors.xml which
get changed when you press the "apply system-wide" button.

Sadly I have not found an easy way to modify the settings for MDM, so you
will have to live with your login screen rotated.

Good luck!


On Tue, Mar 1, 2016 at 10:41 AM, Jesper Öqvist <notifications@github.com>
wrote:

> Here is a screenshot illustrating this issue:
>
> [image: cyhnlq5wqaatq82]
> <https://cloud.githubusercontent.com/assets/2757386/13423262/0e7246dc-df9a-11e5-9037-e4936c00899b.png>
>
> I hope it gets fixed soon. Where is the monitors.xml file by the way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mate-desktop/mate-control-center/issues/198#issuecomment-190636120>
> .
>



-- 
Sten Eriksson
Sibyllegatan 7A, S-752 31 Uppsala, Sweden
Tel +46 739 389 884 [073-938 98 84]

**Comment by alisdt** [comment]
Definitely something to do with the way bounding boxes are computed. By changing the  get_output_rect() in capplets/display/xrandr-capplet.c to use the local get_geometry() function to get width and height, I get better behaviour and can wrangle the screens into the right place. This is not a fix -- the screens still pop about, so there must still be other code directly getting width and height somewhere and doing the wrong thing.

I find it odd that mate_rr_output_info_get_geometry doesn't do the "right" thing for this, but perhaps it's used in other contexts where this wouldn't make sense.

**Comment by monsta** [comment]
Seems related to https://bugzilla.gnome.org/731166. Maybe we'll be able to pick some fixes.
