### ISSUE TITLE
No package 'libmate-menu' found

### ISSUE THREAD

**Issue by mf0hka** [mate-desktop/mate-control-center#199]
During compiling,  running  autogen.sh, the script terminates with "No package 'libmate-menu' found"
I looked in the repo for this, "libmate-menu", but haven't found it. What is this package it is looking for?

I am compiling on debian, using the command $ ACLOCAL_FLAGS="-I /usr/share/aclocal" ./autogen.sh 

should I do something else while trying to compile?

**Comment by monsta** [comment]
```sudo apt-get build-dep mate-control-center```
