### ISSUE TITLE
Gtk3 tracking report

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-control-center#206]
This report list only Gtk3 bugs which needs to be fixed before control-center can use for production with gtk3.
Please open a single report first if you found a new issue, mention there that you think this is a blocker report, and we will add them here.

MUST:
- Gtk3: appearance properties: theme preview glitches
  https://github.com/mate-desktop/mate-control-center/issues/137 fixed https://github.com/mate-desktop/mate-control-center/commit/33ef39610be27cfa487ed82a7bbd10caf3e7bcbd

SHOULD:
- GTK3: mate-appearance-properties, colour change problem
  https://github.com/mate-desktop/mate-control-center/issues/170
Dropped for gtk+-3

NICE TO HAVE:
- Unable to see font characters while using mate-font-viewer
  https://github.com/mate-desktop/mate-control-center/issues/143 
fixed with 1.18

Solution: mate-font-viewer needs to be port to SushiFontloader
done for gtk3 only here 
https://github.com/raveit65/mate-control-center/commit/c2f3c9f5c68f81d3c47cd3d43f7e3c4f06bd6816
https://github.com/raveit65/mate-control-center/commit/f5f6183e71eb839e6abe7dd9d5bdbe68b40aedba
https://github.com/raveit65/mate-control-center/commit/940daef6bbe505134d2c63f2b579f68e5d26694f
##

**Comment by DavidGriffith** [comment]
Where are these bugs described at https://bugzilla.gnome.org?

**Comment by raveit65** [comment]
are we gnome?

**Comment by DavidGriffith** [comment]
I'm not implying that the MATE effort is affiliated with Gnome in any way.  I just want to know if anyone has talked to the Gnome people about GTK+3 not behaving correctly and if so, where is that discussion.

**Comment by raveit65** [comment]
No, nobody did that, feel free to do that.
