### ISSUE TITLE
RFE: mate-preferences-categories.menu belongs to mate-menus

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-control-center#207]
mate-preferences-categories.menu is a layout file and belongs to mate-menus which contains layout files for menus.
https://github.com/mate-desktop/mate-menus/tree/master/layout
This makes it easier to split out the file to a subpackage with a meaningful name for a distro package maintainer.
In fedora i shiped such a file since a long time with a subpackage called
mate-menus-preferences-category-menu
In result a user can decide by installation if he want a category-menu or not,
see http://forums.mate-desktop.org/viewtopic.php?f=17&t=3595
Well,  a package split can also be done with m-c-c, but the resulting name is not meaningful
and very long.
@flexiondotorg @monsta @clefebvre @sunweaver @willysr @posophe 
What do you think?

**Comment by tarakbumba** [comment]
While it is much nicer to have an option to use old menu layout or the new one in mozo; i agree with you that this layout file should be in mate-menus.

**Comment by black77** [comment]
Obviously I can’t speak for all Mate users but personally I would prefer to eliminate categories submenu completely, without having it as a possible option. To my mind such a submenu is superfluous and deprives Mate its initial simplicity.

**Comment by raveit65** [comment]
> Obviously I can’t speak for all Mate users but personally I would prefer to eliminate categories submenu completely, without having it as a possible option. To my mind such a submenu is superfluous and deprives Mate its initial simplicity.

This depends on you your point of view and what distro you use ;)
For example in fedora old gnome2 always use this menu, and i use this categories since the beginning of MATE in fedora.
In result i have no rhbz about that somebody thinks that breaks the default.
For me this is only a new default in debian based distros maybe, for all others this is the default ;)

**Comment by black77** [comment]
My distro is openSUSE Leap, I've used Mate for a couple of years with openSUSE and the Submenu's got to be default only since the beginning of November, this year.
Yes that was just my own opinion:) Again, I wouldn't try to speak for others.

**Comment by monsta** [comment]
> While it is much nicer to have an option to use old menu layout or the new one in mozo

The problem is that all these ```.menu``` files go into ```/etc/xdg/menus``` dir... so it's kind of system-wide setting.
It seems to me that the only way to make them optional is to provide the ```.menu``` file in question in a separate package (which can be installed or removed as user wishes).

**Comment by flexiondotorg** [comment]
I suggest we leave leave the new menu categorisation as it is, because:

  * On some distros, without these categories, the menus scroll over the top and bottom of even a full HD monitor. Which is harder to navigate than the the organised structure.
  * This categorisation is how GNOME2 was intended to be used and several distros, including Fedora and openSUSE, have retained this organisation.
  * If you want a list of everything, the control center does that, and can also be keyword filtered.

If you anyone doesn't like these menus in their distro I suggest they lobby their distro maintainer to patch out the `.menu` file in their builds.

**Comment by raveit65** [comment]
mate-preferences-categories.menu is moved to mate-menus in master branch
https://github.com/mate-desktop/mate-control-center/commit/9e7b0ed69e45d129aa0d720a1e9a4d41b599a794
https://github.com/mate-desktop/mate-menus/commit/38c91676b80675762e9bfad1a43348e6a4cf3af0
You can use those commits as patches for 1.12 packages, and create a subpackage for mate-menu with the file.
This is the way how i handle this in fedora.
Those subpackage is in default installation, but a user can uninstall it if he don't like the categories.
