### ISSUE TITLE
[Regression] Part of icons in control center are inaccesible with HiDPI

### ISSUE THREAD

**Issue by dnord** [mate-desktop/mate-control-center#208]
If you set high dpi in "appearance" (160 for example instead of default 96), then part of icons in control center become inaccesible, as you can not scroll to them. However, if you try to resize control center's window problem disappears.
Things got broken after "libslab: Add GTK3 support" mate-desktop/mate-control-center@80c3d8ace4794481e711fb63e4eefd9f1f5cc1ef

**Comment by dnord** [comment]
Here is the fix for this issue: https://github.com/mate-desktop/mate-control-center/pull/209
please pull

**Comment by monsta** [comment]
Thanks, merged.

**Comment by monsta** [comment]
I've actually got this issue even with the default DPI (96)... dunno why. Anyway, it's fixed now.
