### ISSUE TITLE
Cursor displaying issue

### ISSUE THREAD

**Issue by AntonKarmanov** [mate-desktop/mate-control-center#223]
I'm not shure which one mate module is exactly guilty.
Some time ago I have trouble with changing cursor theme: I switched theme with mate-appearance-properties, but cursor did not change. Then I updated Mate-Desktop with official ppa. Now when I boot system I have a cross instead of an arrow cursor. If I start mate-appearance-properties manually, then cursor become normal view. Also if I start FireFox, it have the same effect. Oh, it seems, the same effect have restarting of mate-panel.
I have Ubuntu Mate 15.10 and Mate-Desktop 1.12.1-1 now.

**Comment by raveit65** [comment]
Sounds like an old issue.
Some distros, ie. fedora set a default cursor theme in /usr/share/icons/default/index.theme.
And some login manager , ie. lightdm, reads from this file and set it to the root window.
We could fix that with patching lightdm in fedora.

**Comment by raveit65** [comment]
Btw. as workaround you can set your cursor theme in /usr/share/icons/default/index.theme.

**Comment by AntonKarmanov** [comment]
Thank you for reply!
I had /usr/share/icons/default/index.theme looks like this:
```
[Icon Theme]
Inherits=DMZ-White
```
But looks like my cursor have a black theme set.
I made string like `Inherits=MATE`, but nothing changed.

**Comment by AntonKarmanov** [comment]
Hmm.. I don know what exactly changed, but now my coursor is OK.

**Comment by flexiondotorg** [comment]
What is in `~/.Xdefaults`?

**Comment by AntonKarmanov** [comment]
I have no such file neither in home folder nor anywhere...

**Comment by AntonKarmanov** [comment]
Now sometimes MATE boots with normal cursor and sometimes with cross.

**Comment by flexiondotorg** [comment]
Are you using Compiz? If so this is a Compiz issue that was recently addressed.

**Comment by AntonKarmanov** [comment]
Oh, yes, right! I just switched to marco, and it seems alright.
Thank you.
