### ISSUE TITLE
GTK3: Display capplet won't open with version-bumped Marco

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-control-center#224]
https://github.com/mate-desktop/marco/commit/054f0fc4ac62613ef5734ac65de6bfe67239b183

Broke opening of the "display" dialog, which errors out on a failure to load libmarco.private.so.0 
As a workaround I made a link by that name to the current libmarco.private and it works

**Comment by monsta** [comment]
Yes, I mentioned that in https://github.com/mate-desktop/marco/pull/252 - a rebuild of m-c-c is needed...
