### ISSUE TITLE
Window bug in control-center [Solved]

### ISSUE THREAD

**Issue by tele1** [mate-desktop/mate-control-center#231]
Maybe 1 year ago I confirmed / reported old problem with the menu,
with small screen resolution, and when is a lot of programs in menu, 
 it is not possible move in  menu mouse, mouse always comes back.

Now I see the same problem with mate-control-center.
I installed manjaro-xfce-16.06-rc1-x86_64.iso from http://manjaro.github.io/download/
I updated and I installed Mate gtk3. ( MATE Desktop Environment 1.12.1 )

In control-center I have a lot of options ( icons ), 
so on the right side of the window I have a scroll bar ,
when I it move, it returns :-(

From terminal I don't see errors
From first run app only

```
$ mate-control-center

** (mate-control-center:18540): WARNING **: 
error raised: [load_xbel_store: couldn't load bookmark file [NULL]
]

```

and from strace I don't see any note, I see 
only  for example 

```
...
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"A\0\227\272\21)\0\4\3\0\202\0\6\0\0\4\0\0\7\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7ffd3360ed40, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffd3360ebf0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffd3360ed20, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}], 3, -1) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"A\0\303\272\33)\0\4\3\0\202\0\6\0\0\4\0p\4\0\0\0\0\0\0\0\0\0\0\0\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7ffd3360ed40, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffd3360ebf0, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffd3360ed20, 0)           = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=9, events=POLLIN}], 3, -1) = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name(0)=NULL, msg_iov(1)=[{"U\2\315\272\225\217P\2\3\4\4\0\0\0\0\0\0\0\0\4\4\4\4\4\0\0\3\37%\2\0\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
recvmsg(3, 0x7ffd3360ed40, 0)           = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, 0x7ffd3360ed20, 0)           = -1 EAGAIN (Resource temporarily unavailable)
...
```

**Comment by monsta** [comment]
Well... I don't get it... "it returns"?

Can you post some screenshots to illustrate the problem?

**Comment by tele1** [comment]
I'll try do video in free time.

**Comment by tele1** [comment]
I'm sorry I did not do the video,
it looked like this:
- I moved the wheel, working
- I moved the scroll bar, I moved mouse / cursor to button, and window returned to the top.
It looked like as a reaction on button. 
(sorry I hope you understand, my english is poor)
Now I don't have this bug after update:
http://wklejto.pl/256403

Tomorrow I'll try to check more.

**Comment by tele1** [comment]
I tested with strace and output  looks like the same like above.
I tested menu, it working properly now.
I downloaded and tested the previous iso on virtualbox - I don't see this bug.
I used iso xfce and Mate I installed from repository,
   so maybe problem was with dependencies, I don't know.
Output from terminal looks now
```
$ mate-control-center

** (mate-control-center:3997): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

** (mate-control-center:3997): WARNING **: 
error raised: [load_xbel_store: couldn't load bookmark file [NULL]
]

```

**Comment by monsta** [comment]
Ok, good it's solved.
