### ISSUE TITLE
Migrate mate-control-center to GtkApplication

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-control-center#237]
Debian has raised the following bug:

  * **mate-control-center** - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827230

This MATE component needs migrating to GtkApplication:

  * https://developer.gnome.org/gtk3/3.20/gtk-migrating-unique-GtkApplication.html

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-control-center/pull/253

**Comment by monsta** [comment]
#253 is merged now, closing.
