### ISSUE TITLE
Some applications names "not translated"

### ISSUE THREAD

**Issue by rogue-spectre** [mate-desktop/mate-control-center#239]
Hi,

 i noticed that on linux mint (17 and beta 18 64bits) and ubuntu-mate ( 16.04 64bits), some applications (network, printer, users and groups…) showed on the mate-control-center have their name and description not translated (tested in french and spanish) whereas translation is done when you access the application by the classic menu or mate menu.

##

**Comment by monsta** [comment]
Ok, so these are apps from ```gnome-system-tools``` and ```system-config-printer``` packages I guess.
I can't reproduce it in Debian edition of Mint (LMDE) with Russian locale. I'll check it in Mint 17 and 18 later.

**Comment by monsta** [comment]
@flexiondotorg: have you encountered this issue in Ubuntu MATE?

**Comment by rogue-spectre** [comment]
It seems that there is one
https://bugs.launchpad.net/ubuntu-mate/+bug/1594959

**Comment by monsta** [comment]
Ok, I see it in Mint 17 and Ubuntu 16.04... not sure how I didn't pay attention to it before.

**Comment by rogue-spectre** [comment]
Hi,
    for French people who wants to "solve" temporary the problem i put the translations directly in the .desktop in the archive 

[modifs_desktop_files.zip](https://github.com/mate-desktop/mate-control-center/files/359057/modifs_desktop_files.zip)


 
[Uploading modifs_desktop_files.zip…]()

**Comment by monsta** [comment]
Looks like this is an issue with MateDesktopItem API from libmate-desktop. It parses the .desktop file directly and looks for fields like Name[ru], Comment[ru], etc.

**Comment by monsta** [comment]
Try https://github.com/mate-desktop/mate-control-center/pull/314 for a possible fix.
