### ISSUE TITLE
[patch] mate-about-me looks ugly

### ISSUE THREAD

**Issue by rogue-spectre** [mate-desktop/mate-control-center#240]
Hi,

in linuxmint 18 32bits, mate-control-center 1.14.0-1
in ubuntu-mate 64 bits, mate-control-center 1.12.2-1
     
mate-about-me looks ugly… it seems to lack some space 

![capture_mate-about-me](https://cloud.githubusercontent.com/assets/2879782/16507903/f61fd57e-3f2d-11e6-83a1-803f16fd663e.png)

**Comment by rogue-spectre** [comment]
Hi,
       Here a little patch

 [patch.diff.zip](https://github.com/mate-desktop/mate-control-center/files/378371/patch.diff.zip)

to add some space after the bold username. I put a 48px (12px is the spacing between the picture box and the bold username so the spacing must be at least 12px) +. A little capture to see the difference :
    
![before_after](https://cloud.githubusercontent.com/assets/2879782/17059953/ef27e06c-5027-11e6-8f53-10c0932d3b9d.png)

**Comment by raveit65** [comment]
Can you do a pull request please?

**Comment by monsta** [comment]
Thanks, closing as the patch is merged now.
