### ISSUE TITLE
mate-about-me hangs if error is made modifying password

### ISSUE THREAD

**Issue by rogue-spectre** [mate-desktop/mate-control-center#241]
Hi,

in linuxmint mate 18 32bits, mate-about-me 1.14.0-1

I noticed that if you make a mistake trying to change your password via mate-about-me, the interface hangs. since the other graphical way to change the user password (users-admin https://bugs.launchpad.net/ubuntu/+source/gnome-system-tools/+bug/661272… maybe the idea of the patch could be apply here… i think) hangs also when making mistakes… it seems important to solve the problem ;)

**Comment by rogue-spectre** [comment]
at line 511 of mate-about-me-passwd.c, there is a missing coma.

`						  "recent",`

**Comment by monsta** [comment]
Looks like fix is merged now, so I'm closing this.
