### ISSUE TITLE
mate-keybinding-properties hangs if $XDG_RUNTIME_DIR/dconf/user has incorrect permissions

### ISSUE THREAD

**Issue by ioaoue** [mate-desktop/mate-control-center#246]
Linux Mint 18
mate-control-center: 1.14.0-1+sarah

Under some circumstances (https://bugs.debian.org/732209 for example) file $XDG_RUNTIME_DIR/dconf/user gets owned by root. Then mate-keybinding-properties tries to create it in an infinite loop and consumes all available memory. It may be critical if swap is enabled.

stderr output:
```
...
(mate-keybinding-properties:21392): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.

(mate-keybinding-properties:21392): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.

(mate-keybinding-properties:21392): dconf-CRITICAL **: unable to create file '/run/user/1000/dconf/user': Permission denied.  dconf will not work properly.
...
```

Other Control Center applets output the same error but do not hang.

**Comment by raveit65** [comment]
Congratulation,
you are another victim of an old systemd bug, see https://bugzilla.redhat.com/show_bug.cgi?id=753882
https://launchpad.net/bugs/1197395
Sadly, those devs gives a shit about since 2011-11-14 !!!!
I suggest to file out a report in linuxmint, sorry we can nothing do here.
@clefebvre ^^^^^^

**Comment by clefebvre** [comment]
omg.. this again.

We've patched this for 2 years in 17.x.

In 18 we're using the same libpam-systemd as Ubuntu (xenial).

**Comment by ioaoue** [comment]
I understand why this happens. My question was: why mate-keybinding-properties hangs so that only kill -9 helps? Maybe it could show some error to the user and then close?

**Comment by clefebvre** [comment]
It's not really an issue with the software itself. When the runtime dir isn't writeable, dconf itself starts acting really weird.
