### ISSUE TITLE
Xrandr capplet broken by glib 2.49.6

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-control-center#251]
GTK 3.21.5 is shipped in Debian Unstable with glib 2.49.6, which is required to build current versions of GTK3.21. Unfortunately, the display (xranxdr) capplet's GUI gets a black square for the primary monitor, has no response to "detect monitors," and does not display any secondary monitors that are connected.

Primary monitor resolution can be changed but other monitors cannot be interacted with and are not displayed. Checking, then unchecking the box for "same image in all monitors" will enable the option to turn off the primary monitor but that is of little use w/o secondary monitors shown.

The tray applet functions as normal but does not include the ability  to turn secondary monitors on or off.  With two monitors connected,  two sets of menu options are shown, each controls orientation on the same monitor as with the older glib version, but they are not named and with the option to turn monitors on and off not included in the tray applet this does not provide a workaround.

Rolling back the glib version to 2.49.5 restores full function, but current GTK 3.21 from master requires glib 2.49.6.  Arandr can be used as a workaround for now.

**Comment by raveit65** [comment]
Damned, i don't have a second monotor to bisect it.

**Comment by lukefromdc** [comment]
Turns out both the GNOME and the Cinnamon versions of the same capplet work. I will go looking for the commit that made the difference.

**Comment by lukefromdc** [comment]
This commit predates the GNOME-Cinnamon split and involves switching away from glib-dbus to gdbus, and the problem we are having looks like a partial connection where the capplet can't receive at least some of the screen information:

https://github.com/GNOME/gnome-control-center/commit/89bbb0a73abab6935016c1999dedac4cee56caa3
 display: Use GDBus instead of dbus-glib 

It's relatively complicated to apply this directly to our version of xrandr-capplet.c due to other differences, but I'll have to play with that. Several simpler commits from GNOME and Cinnamon had no effect when applied but at least indicate that cross-pollination is possible here

**Comment by lukefromdc** [comment]
Got these warnings on selecting "display" after running mate-control-center from the command line, the last three are not the usual ones we get:

```
(mate-display-properties:14154): Gtk-CRITICAL **: gtk_widget_modify_fg: assertion 'state >= GTK_STATE_NORMAL && state <= GTK_STATE_INSENSITIVE' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(mate-display-properties:14154): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate toplevel GtkDialog 0x9c42b0. Allocation is 463x319, but minimum required size is 572x319.

(mate-display-properties:14154): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate GtkDialog's child GtkBox 0x9ca750. Allocation is 453x309, but minimum required size is 562x309.

(mate-display-properties:14154): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to underallocate GtkBox's child GtkTable 0x9cd700. Allocation is 449x276, but minimum required size is 558x276.

(mate-display-properties:14154): display-properties-CRITICAL **: foo_marshal_VOID__POINTER_BOXED_POINTER: assertion 'n_param_values == 4' failed

(mate-display-properties:14154): display-properties-CRITICAL **: foo_marshal_VOID__POINTER_BOXED_POINTER: assertion 'n_param_values == 4' failed

(mate-display-properties:14154): display-properties-CRITICAL **: foo_marshal_VOID__POINTER_BOXED_POINTER: assertion 'n_param_values == 4' failed
```

Also, if you have Cinnamon installed, cinnamon-control-center display works normally even from a MATE session, so I suspect the dbus issue now more than ever.

**Comment by lukefromdc** [comment]
Applying as much as https://github.com/GNOME/gnome-control-center/commit/89bbb0a73abab6935016c1999dedac4cee56caa3 as I was able to had no effect at all, but this is not conclusive as a failed part might refuse to connect, giving the same results as before

**Comment by lukefromdc** [comment]
I was just able to build a version that worked by replacing the capplets/display/scrollarea.c and scrollarea.h files with the versions from cinnamon-control-center and editing one function in xradr-capplet.c. Now I just need to find out what changed so a patch for the mate versions of these files can be created, might be possible to bisect from old g-c-c commits, maybe I'll just have to go function by function but some changes are interdependent.

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-control-center/pull/252 fixes this-it came down to a single line, systematic removal of lines between the Master and a gnome-control-center 3.0 version of scrollarea.c found it

**Comment by raveit65** [comment]
I just see the issue now with f25 and testing the fix.

**Comment by monsta** [comment]
So looks like https://github.com/GNOME/gnome-control-center/commit/89bbb0a73abab6935016c1999dedac4cee56caa3 isn't needed?

**Comment by monsta** [comment]
Since this is related to custom marshalling code, I suspect this commit:
https://git.gnome.org/browse/glib/commit/?id=ef16cbee5bfb4378ca40a2e034c66539f222b22a

Need to bisect commits between 2.49.5 and 2.49.6 to be sure...

**Comment by lukefromdc** [comment]
That is confirmed: at first I thought glib-dbus had been broken (it got work
this cycle in glib) but I tested applying that commit without results, then 
kept looking until I found out what had really broken

**Comment by lukefromdc** [comment]
Can anyone confirm whether or not the current master code works with GTK2 and glib 2.49.6 or later? If it does we can put this behind GTK3 selectors and be done with it.

**Comment by monsta** [comment]
> Since this is related to custom marshalling code, I suspect this commit:
https://git.gnome.org/browse/glib/commit/?id=ef16cbee5bfb4378ca40a2e034c66539f222b22a

> Need to bisect commits between 2.49.5 and 2.49.6 to be sure...

Alright, ```git bisect``` showed I was correct. That commit broke it.

**Comment by monsta** [comment]
I've posted a comment about it at https://bugzilla.gnome.org/769076.

**Comment by monsta** [comment]
Ok, so we need either ```foo_marshal_VOID__POINTER``` (which isn't written in ```foo-marshal.c``` yet) or ```g_cclosure_marshal_VOID__POINTER``` - in other words, fix in https://github.com/mate-desktop/mate-control-center/pull/252 seems to be the correct solution. I'll test the edited PR later.
