### ISSUE TITLE
Change theme fonts and background colors in "Other settings"

### ISSUE THREAD

**Issue by colibris79** [mate-desktop/mate-control-center#255]
Hi, 
I am not sure if this is the right place to post this (or maybe the "mate-themes" place...), so my apologies if   it is not. I am using Linux Mint 17.3 and when I personalize a theme through "Control center/Appearance/Themes/Other settings" sometimes I can modify the colors in the "Colors" tab and sometimes I can't (most of the times I can't, only the Windows-background color is editable).  I have been trying to figure out why this happens but so far I have no idea. I know I can manually modify the colors in my user/.themes folder but it is much slower to find the right color. 
Any ideas? Thanks

**Comment by raveit65** [comment]
This works only with gtk2 applications, gtk3 theming is to complex for this simple gui.
With Mate gtk3 the color page is disabled.
Time to forget this feature.
Btw. there is another report about, so closing this one.

**Comment by colibris79** [comment]
Thanks for your answer!


________________________________
De: raveit65 <notifications@github.com>
Enviado: martes, 25 de octubre de 2016 14:16
Para: mate-desktop/mate-control-center
Cc: colibris79; Author
Asunto: Re: [mate-desktop/mate-control-center] Change theme fonts and background colors in "Other settings" (#255)


This works only with gtk2 applications, gtk3 theming is to complex for this simple gui.
With Mate gtk3 the color page is disabled.
Time to forget this feature.
Btw. there is another report about, so closing this one.

-
