### ISSUE TITLE
mate-appearance-properties: mounse pointer size slider greyed out

### ISSUE THREAD

**Issue by quite** [mate-desktop/mate-control-center#256]
As per https://ubuntu-mate.community/t/support-for-cursors-with-multiple-sizes/1356/2 

This seems to be the case still. The pointer size slider (smaller/larger) is not enabled/disabled (grey out) to reflect whether the currently selected pointer theme supports different sizes or not. 
##

**Comment by monsta** [comment]
Ok, it's fixed now, and I will also backport it to 1.16.
