### ISSUE TITLE
Add support for external localization of installed tools

### ISSUE THREAD

**Issue by FallenPhoenix** [mate-desktop/mate-control-center#260]
I just finished to edit desktop-files for Control Center in Linux Mint 18.
Some entries of default system tweaks shows localized everywhere but Control Center. The problem is Mint (same as Ubuntu) uses external mo-files (gettext) for build-in shortcuts, which is part of language pack. But there no localizations inside shortcut (.desktop) files itself.

For example, my current locale is Russian.
I've seen Russian string for printer settings in main menu and inside "/usr/share/applications" folder, but English string in Control Center. Let's see why.
/usr/share/applications/system-config-printer.desktop:
```
[Desktop Entry]
Name=Printers
Comment=Configure printers
Exec=system-config-printer
Terminal=false
Type=Application
Icon=printer
StartupNotify=true
NotShowIn=KDE;GNOME;
X-Ubuntu-Gettext-Domain=system-config-printer
Categories=GNOME;GTK;Settings;HardwareSettings;X-GNOME-Settings-Panel;X-Unity-Settings-Panel;System;Printing;
X-GNOME-Settings-Panel=printing
X-Unity-Settings-Panel=printing
Keywords=Printer;Queue;Print;Paper;Ink;Toner;
X-Desktop-File-Install-Version=0.22
```
As you can see, there no Name[ru] or Comment[ru] fields, but there "X-Ubuntu-Gettext-Domain=system-config-printer" instead. Next I found file "/usr/share/locale-langpack/ru/LC_MESSAGES/system-config-printer.mo" and name/comment translation entries for that:
```
msgid "Printers"
msgstr "Принтеры"

msgid "Configure printers"
msgstr "Настроить принтеры"
 ```
I edited desktop entry file with adding Russian strings of name and comment (gksu pluma system-config-printer.desktop):
```
[Desktop Entry]
Name=Printers
Name[ru]=Принтеры
Comment=Configure printers
Comment[ru]=Настроить принтеры
...
```
And Control Center became show that tweak on Russian language.

So MATE Control Center seems loads internal translations fine, but not external ones. Could you add support for that? I think, it simplest way to see it translated "from box".

---

**bountysource-plugin**

Want to back this issue?
**[Post a bounty on it!](https://www.bountysource.com/issues/38940334-feature-request-add-support-for-external-localization-of-installed-tools?utm_campaign=plugin&utm_content=tracker%2F559197&utm_medium=issues&utm_source=github)**
We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F559197&utm_medium=issues&utm_source=github).

**Comment by monsta** [comment]
Попробуйте https://github.com/mate-desktop/mate-control-center/pull/314, должно сработать.
Закрываю, т.к. повтор https://github.com/mate-desktop/mate-control-center/issues/239

**Comment by raveit65** [comment]
I do not have an external desktop-file **with localisation** installed, which don't display in my language.
And mentioned system-config-printer is translated here.

**Comment by monsta** [comment]
It's ok, if you don't have Ubuntu VMs, it's enough to check there are no regressions in Fedora (or other distros).

**Comment by raveit65** [comment]
> It's ok, if you don't have Ubuntu VMs, it's enough to check there are no regressions in Fedora (or other distros).

Ok, let's wait for Martins review.
