### ISSUE TITLE
mate-default-applications-properties: Default file manager option doesn't work

### ISSUE THREAD

**Issue by danboid** [mate-desktop/mate-control-center#263]
I'm running the GTK3 build of MATE 1.16.1 under Arch Linux. I have the File Manager setting under the System tab of mate-default-applications-properties set to use Thunar instead of Caja as the default File Manager but MATE still opens Caja when I insert a removeable drive or if I click on any folders on the  desktop.

**Comment by monsta** [comment]
Yes, these features are still handled by Caja. We have a report at https://github.com/mate-desktop/caja/issues/388.
