### ISSUE TITLE
mate-appearance-properties inner frame (box) should expand vertically too

### ISSUE THREAD

**Issue by ThanosApostolou** [mate-desktop/mate-control-center#264]
Sorry if this had been reported somewhere else (I couldn't find anything similar).

When you resize the mate-appearance-properties window, then inner frame expands horizontally together with the window, but it doesn't expand vertically. See images below:
http://imgur.com/a/TvIBN
http://imgur.com/a/n5RWn

In the second image, the inner box should expand in a way that "Get more themes online" is just above the "Help" button and the buttons "Save As", "Customize",... should be just above the "Close" button.

This is happening on Ubuntu MATE 16.10 and manjaro MATE edition on MATE 1.16 gtk3 build.

**Comment by raveit65** [comment]
weird, this is working in fedora with gtk3
![bildschirmfoto zu 2017-01-08_14-45-21](https://cloud.githubusercontent.com/assets/961604/21750337/387ec3ca-d5b1-11e6-9ed0-d8dbbfc86f08.png)

**Comment by ThanosApostolou** [comment]
I noticed the same behaviour with mate-session-properties (Startup Applications Preferences):
![screenshot at 2017-01-08 16-01-41](https://cloud.githubusercontent.com/assets/21288843/21750450/1cf4ec50-d5bc-11e6-8ece-4f956b3656c0.png)

I will download and try with fedora later.

**Comment by raveit65** [comment]
session-properties was fixed with 1.17
https://github.com/mate-desktop/mate-session-manager/commit/f15be61545192568dfcb438d3452d637f08001ab

**Comment by ThanosApostolou** [comment]
Aaaa nice. Any chance that this will get into 1.16?

**Comment by raveit65** [comment]
opps, the issue still exists with latest 1.16.0 in f25, but not with latest 1.17 from master here.
But i don't see a commit for it in master branch.

**Comment by raveit65** [comment]
i mean with m-c-c

**Comment by raveit65** [comment]
well, it is a bugfix and we backport bug fixes sometimes.

**Comment by monsta** [comment]
Hmm...

Ubuntu MATE 16.10, m-c-c 1.16.0, GTK+ 3.20.9: not reproduced
Ubuntu MATE 17.04, m-c-c 1.17.1, GTK+ 3.22.7: reproduced

**Comment by ThanosApostolou** [comment]
I see it too. On Ubuntu MATE 17.04 (daily build) `mate-session-properties` is fixed, but `mate-appearance-properties` isn't.

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/mate-control-center/commit/ec26fcb96d1d4b8433cff656cc2df8da1de55e4d should fix it.
You can test it locally without rebuilding the package - just edit ```/usr/share/mate-control-center/ui/appearance.ui``` (as root) and add that line.

**Comment by ThanosApostolou** [comment]
@monsta Yep that did the trick! Feel free to close this whenever you want.
