### ISSUE TITLE
mate-default-applications-properties: No apps in the Accessibility tab [$100]

### ISSUE THREAD

**Issue by cwendling** [mate-desktop/mate-control-center#270]
At least under current Debian and Ubuntu nothing shows there, even though Orca is installed and should show in the *Visual* dropdown.

This seems to be due to Orca no longer providing *orca.desktop* under */usr/share/applications/* (nor anywhere else), but only the autostart file.  I'm not sure how this should be done now, but a change is required.

**Comment by monsta** [comment]
Yes, I see this issue in Debian Testing. Indeed, Orca 3.22 comes without .desktop file (after [this commit](https://git.gnome.org/browse/orca/commit/?id=500d4ca4a984b17dcf3e83d4fa796ac62b9cae45)).

I wonder if we should keep that option at all. First, I'm not sure if there's an alternative to Orca that could be "switched" there like you switch your text editor or video player. Second, there's a checkbox saying "run at start" which actually does nothing - you can check it on and off, then look into mate-session-properties and see that nothing was changed about Orca autostart there. :slightly_smiling_face:

**Comment by raveit65** [comment]
I guess the 'run at start' option is for generating and autostart file for an application which don't use already a /etc/xdg/autostart/*.desktop file.
As orca ships their own autostart file it is useless here.
But from f25 (gtk+-3.22)
```
[Desktop Entry]
Type=Application
Name=Orca screen reader
Exec=orca
NoDisplay=true
AutostartCondition=GSettings org.gnome.desktop.a11y.applications screen-reader-enabled
X-GNOME-AutoRestart=true
#X-GNOME-Autostart-Phase=Initialization
OnlyShowIn=GNOME;MATE;Unity;Cinnamon;
```
But will orca really start if 'org.gnome.desktop.a11y.applications screen-reader-enabled' isn't installed or not enabled?

**Comment by vkareh** [comment]
https://www.bountysource.com/issues/42364891-mate-default-applications-properties-no-apps-in-the-accessibility-tab

**Comment by alexarnaud** [comment]
@vkareh Do you plan to work on this?

Best regards,
Alex.

**Comment by flexiondotorg** [comment]
This is not a MATE bug to fix. Upstream Orca is no longer shipping orca.desktop since Orca 3.22. The rationale is explained here:

  * https://gitlab.gnome.org/GNOME/orca/commit/500d4ca4a984b17dcf3e83d4fa796ac62b9cae45

The advice, also taken from the commit comment above, is that distro who require `orca.desktop` ship it themselves. The following desktop file works if you place it in `/usr/share/applications/orca.desktop`

```
[Desktop Entry]
Name=Screen Reader
GenericName=Screen Reader
X-GNOME-FullName=Orca Screen Reader
Comment=Provide access to graphical desktop environments via synthesized speech and/or refreshable braille
Keywords=screen reader;speech;braille;
Exec=orca --replace
Icon=orca
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;GNOME;Utility;Accessibility;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=orca
X-GNOME-Bugzilla-Component=general
OnlyShowIn=MATE;
```

@monsta @raveit65 @vkareh Should we close this issue?

**Comment by raveit65** [comment]
Guys, are you satisfied or do you expect to see more applications than orca?
@rbuj 
When problem is solved you should claim this nice bounty https://www.bountysource.com/issues/42364891-mate-default-applications-properties-no-apps-in-the-accessibility-tab
