### ISSUE TITLE
mouse cursor feature "show position of mouse cursor when control key is pressed" causing black square around cursor

### ISSUE THREAD

**Issue by geki-yaba** [mate-desktop/mate-control-center#278]
Well, I cannot say where the issue exactly is and if it belongs to this MATE project.

My system is a Sandybridge CPU/GPU with latest xorg/xf86-video-intel driver, GLAMOUR disabled.

Demonstrated best by video:
http://geki.selfhost.eu/files/mouse_press_ctrl_key.mkv

Reported to xf86-video-intel driver at freedesktop.org, because I guess the driver is involved:
https://bugs.freedesktop.org/show_bug.cgi?id=93567

Would you be so kind to point me to the source code that is executed for the above-mentioned feature, please?

Thank you very much in advance!

**Comment by monsta** [comment]
The pointer locater functionality is in mate-settings-daemon, and the drawing issues had been fixed in versions 1.18.1 and 1.16.2.
