### ISSUE TITLE
Gnome Themes no longer available on Appearance dialog

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-control-center#288]
#### Expected behaviour
When GNOME Themes Standard is installed on the system GNOME themes should be visible on Mate appearance dialog.

#### Actual behaviour
Since gnome Themes Standard 3.22.3 (available on Debian Sid and Ubuntu 17.10) GNOME themes no longer appear on the Mate appearance dialog

#### Steps to reproduce the behaviour
1) Install GNOMEE Themes last release (3.22.3), on Debian/Ubuntu for example the package gnome-accessibility-themes
2) Open the Appearance window
3) Search for theme from NighContrast theme

#### MATE general version
1.16

#### Package version
1.16.1-1

#### Linux Distribution
Debian Sid

#### Explanation
GNOME Themes Standard drops the support for the key Metacity in [the commit 0fb555d0bc1b78c7f208e7f4adcf65e35f72cfc3t](https://github.com/GNOME/gnome-themes-standard/commit/0fb555d0bc1b78c7f208e7f4adcf65e35f72cfc3)

Best regards.

**Comment by raveit65** [comment]
mate-appearance-properties expected min. 3 values, gtk-theme, metacity-theme and icon-theme.
When gnome dropped one of them than they don't want that users use their themes in other desktop, or do you want to say that those Overloards make mistakes?  ;-)
In any case we can fix their issues. I suggest to open a report at gnome bugzilla and ask them to revert this commit or better to implement a metacity theme again.
Any ways, you can select the gnome gtk-theme if you click on the **edit** button.
So closing this....

**Comment by alexarnaud** [comment]
Le 28/06/2017 à 15:35, raveit65 a écrit :
> mate-appearance-properties expected min. 3 values, gtk-theme, 
> metacity-theme and icon-theme.

Sorry I don't understand why we need Metacity theme. GTK Theme key 
couldn't be sufficient ? (so I haven't your understanding and knowledge 
about the context)

> In any case we can fix their issues. I suggest to open a report at gnome 
> bugzilla and ask them to revert this commit or better to implement a 
> metacity theme again.
> Any ways, you can select the gnome gtk-theme if you click on the *edit* 
> button.

It's why I don't understand why we need the Metacity Theme key if we 
could use the theme by the customize button. It's less user-friendly.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
> Sorry I don't understand why we need Metacity theme. GTK Theme key couldn't be sufficient ? (so I haven't your understanding and knowledge about the context)

mate-appearance-properties displays thumbnails in theme view tab.
This does not work any more if one component is missing
For this reason you saw always a big question mark for adwaita theme in the past before the removed the non existing metacity theme from index.theme file.

**Comment by raveit65** [comment]
Moving this report to mate-themes as it affect HighContrast theme too.
I couldn't imagine that i start write index.theme files to fix gtk+ themes in MATE......., wtf
