### ISSUE TITLE
mate-font-viewer is showing a black box instead of fonts (Debian 9)

### ISSUE THREAD

**Issue by MarioMey** [mate-desktop/mate-control-center#292]
#### Expected behaviour
mate-font-viewer should show fonts in the main window, like this (from Google Images):
![imagen](https://user-images.githubusercontent.com/4954109/28524809-64cd82bc-7058-11e7-9d79-3ea07fc75a26.png)

#### Actual behaviour
It shows a black box, no font is visible.
![imagen](https://user-images.githubusercontent.com/4954109/28524828-7e2fcfc6-7058-11e7-86cd-87b3e3d5adda.png)

#### Steps to reproduce the behaviour
Install Debian-Mate 9, double click on a font or use command: ```mate-font-viewer font.ttf```

#### MATE general version
MATE Desktop Environment 1.16.2

#### Package version
mate-control-center 1.16.1-1

#### Linux Distribution
Debian 9 with Mate desktop

#### Link to downstream report of your Distribution
Don't know what this ^ means.

**Comment by mrkafk** [comment]
Exact same situation here.

**Comment by brdjns** [comment]
Any updates on this? I've been having this problem for months now. Debian 9 with Mate Desktop Environment 1.16.2 and mate-control-center-1.16.1-1.

**Comment by albuck** [comment]
The same problem.

**Comment by lukefromdc** [comment]
With Mate 1.22 (locally compiled) on Debian Unstable, mate-font-viewer works fine.

**Comment by vkareh** [comment]
@albuck - all these reports are for MATE 1.16, which is not supported. On what version are you experiencing this?

**Comment by MarioMey** [comment]
Yes, I have Mate 1.16.2, from Debian Stretch updated. I should install a newer version... but not for now.

Thanks.

**Comment by albuck** [comment]
The same Mate 1.16.2 on Debian Stretch. Debian must update Mate on Stretch.

**Comment by mbkma** [comment]
This issue should be solved by now. If not, I am happy to reopen.
