### ISSUE TITLE
search icon misaligned

### ISSUE THREAD

**Issue by faupruclie** [mate-desktop/mate-control-center#299]
#### MATE general version
1.18

#### Package version
1.18.2-2

#### Linux Distribution
Fedora 26

the search icon (inside the search input box, on the right side) is not aligned properly (affects all themes):
![mate-control-center-search-icon](https://user-images.githubusercontent.com/30813872/29049247-d63e69ac-7ba2-11e7-981e-c10910941f1e.png)

it should be vertically centered

**Comment by raveit65** [comment]
I am thinking about to use the **find** icon from themes, and drop the builtin construct.
![mcc-search](https://user-images.githubusercontent.com/961604/29058098-df35f6a8-7c0e-11e7-9344-e1a30188135b.png)

**Comment by flexiondotorg** [comment]
@raveit65 I agree with your idea.

**Comment by faupruclie** [comment]
sounds okay to me

**Comment by zhangxianwei8** [comment]
How about using GtkSearchEntry since gtk 3.6.
https://developer.gnome.org/gtk3/stable/GtkSearchEntry.html
![search](https://user-images.githubusercontent.com/33945019/34765950-d4551392-f62d-11e7-88be-894cf3588ad7.png)
@raveit65 @flexiondotorg
