### ISSUE TITLE
"Pick a font" new design proposal

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-control-center#303]
Dear team,

I'm currently testing Mate 1.18 to migrate my old Debian Jessie and I test personalization features as a regular user perspective.

#### Issues in my opinion
Otherwise I don't find the new design as user friendly as it was before (version 1.8) for multiple reasons:
1) There are no visible labels for font family and font size so the user needs to know this is a font family and font size respectively at the top and bottom of the screen
2) It is hard to scroll up and down on the font view because there are four item by font, one by font style (regular, bold, italic, bold italic) so if the number of fonts is important it could become really hard to find the font you want to use
3) The text extract "the quick brown" takes too much place on the screen and makes the scroll harder

##### proposal 1
1) Adding visible label on each part of the interface to ensure the simplicity of the interface
2) Split the font family and font style into two fields to simplify the scroll manipulation
3) Move the font preview at the bottom of the dialog because it's more consistent to have the preview after the font size configuration
4) Drop the font extract "the quick brown" and replace it by on-the-fly preview on the currently keyboard selected item or when the mouse is over.

##### proposal 2
Allow the user to choose between the new design and the old one

Best regards.

**Comment by alexarnaud** [comment]
I've updated the first comment to include remark about font preview

**Comment by monsta** [comment]
Isn't it a font chooser dialog from GTK+?

**Comment by alexarnaud** [comment]
Le 25/08/2017 à 15:58, monsta a écrit :
> Isn't it a font chooser dialog from GTK+?

Indeed, e.g. 
https://developer.gnome.org/gtkmm-tutorial/stable/sec-font-chooser-dialog.html.en

Sorry for the inconvenience. I'll report to GTK guys.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by alexarnaud** [comment]
I've reported the issue on the GNOME bug tracker, see [new design proposal](https://bugzilla.gnome.org/show_bug.cgi?id=786809)

**Comment by monsta** [comment]
I wonder if they will listen...

**Comment by mrnhmath** [comment]
IMVHO they should revert to the GTK2 design, it was more familiar and straight to the point.

**Comment by alexarnaud** [comment]
Le 13/09/2017 à 05:09, mrnhmath a écrit :
> IMVHO they should revert to the GTK2 design, it was more familiar and 
> straight to the point.

I agree with you but I'm not sure GTK devel will accept this proposal, 
we should find a compromise between the GTK2 design and the GTK3 one. 
They want me to send them a mockup, I need to take time for that, if you 
want to help me to create it, you can.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"
