### ISSUE TITLE
Pointer slider is not updatable with left/right arrows [15$]

### ISSUE THREAD

**Issue by alexarnaud** [mate-desktop/mate-control-center#304]
#### Expected behaviour
The pointer slider should be editable with left/right arrows as it is possible with other slider (sound) on the Mate desktop.

#### Actual behaviour
The slider to increase/decrease the pointer size is not modifiable with the keyboard. Using left/right produces no effect.  Origin/end works correctly.

#### Steps to reproduce the behaviour
1) Open appearance
2) Open personalize 
3) Go to the pointer tab
4) Move the keyboard cursor to the pointer size slider with tab
5) Press right or left arrow

#### MATE general version
1.8 on Debian Jessie and 1.18 on Ubuntu 17.10

#### Linux Distribution
Both Ubuntu 17.10 and Debian 8.9.

Best regards.

**Comment by raveit65** [comment]
Hmm, this is working here with all supported fedora versions?
Version with oldest f25:
[rave@f25 ~]$ rpm -qa mate-contr*
mate-control-center-filesystem-1.18.2-2.fc25.x86_64
mate-control-center-1.18.2-2.fc25.x86_64
And it works out of box with latest master version on fedora 26.

Well. outline (visual selecting sign) support needs to be improved for sliders with our themes, but it works in fedora.
To be sure, you're talking about the mouse properties tab?

**Comment by alexarnaud** [comment]
Le 02/09/2017 à 18:58, raveit65 a écrit :
> Hmm, this is working here with all supported fedora versions?
> Version with oldest f25:
> [rave@f25 ~]$ rpm -qa mate-contr*
> mate-control-center-filesystem-1.18.2-2.fc25.x86_64
> mate-control-center-1.18.2-2.fc25.x86_64
> And it works out of box with latest master version on fedora 26.

What do you mean by it works? Do you mean you are able to change the 
mouse pointer size with left and right arrows?

> Well. outline (visual selecting sign) support needs to be improved for 
> sliders with our themes, but it works in fedora.
> To be sure, you're talking about the mouse properties tab?

The tab is named "pointer" in the theme customization dialog.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by raveit65** [comment]
ok, you mean mate-appearance-properties dialog.
Confirmed, i see that the slider is selected, but you you can't move them with left/right arrow keys.

**Comment by alexarnaud** [comment]
@raveit65 @vkareh @monsta FYI, I've added a bounty on this.

Best regards,
Alex.

**Comment by vkareh** [comment]
https://www.bountysource.com/issues/48917885-pointer-slider-is-not-updatable-with-left-right-arrows

**Comment by raveit65** [comment]
I don't think that bountysource is really useful for European devs.
bounty from you
- 10% fee to bountysource
- 1-2% fee for paypal transaction
- the baddest currency exchange rate from dollars to euro by paypal i ever say.
Paypal is really greedy now a days.

**Comment by alexarnaud** [comment]
@raveit65 Indeed, it looks like it's not really good. What's alternative do you prefer?

**Comment by raveit65** [comment]
Well we have our own site for donations https://mate-desktop.org/donate/
But here a donation isn't bind to specific bug fix.
I don't know if @flexiondotorg like to forward donations for a specific report.
I think the easiest way would be that you post to a report that you'll donate a fix for it.
And if someone fix the issue make a private transaction.

**Comment by lukefromdc** [comment]
Bountysource is also no longer usable for those of us who do not have or want Paypal accounts at all.

**Comment by monsta** [comment]
I'm not sure there are other services like bountysource, where people can put money on specific bugs or tasks...

**Comment by raveit65** [comment]
For me the problem is the double fee by paypal (transaction + hidden worst currency exchange fee)
I had a talk with bountysource support, and the told me that they have also pay a fee to paypal if someone did a donation.
In other words paypal sucks money at 3 points from a donation.
I think it is OK if bountysource gets an fee from a donation because they provide and handle the service.
Last time i got 7,68 € from a 10 $ donation, here the fee doesn't look very much.
But imagine a donation is about 100 $ than a lot of money is lost.
Only for sending money from one server to another server.......

**Comment by alexarnaud** [comment]
@monsta @lukefromdc @raveit65 @vkareh I've found those alternative: https://alternativeto.net/software/bountysource/

Let me know if I could donate for solving this issue. I know I donate for specific bug but I couldn't find other solution. Each time a blind user told me he can't do that or that I think it's not normal it's why I'm trying to focus on a11y because other users are mostly concerned by other stuff (that are also important).

Thanks for your time and your great :).

Best regards,
Alex.

**Comment by raveit65** [comment]
@alexarnaud 
The question is how they handle payments.
Eg. FreedomSponsors from your link:
https://freedomsponsors.org/faq#I%20don't%20have%20a%20Paypal%20account%20or%20a%20Bitcoin%20wallet,%20is%20that%20ok?
```

I don't have a Paypal account or a Bitcoin wallet, is that ok?

To be able to receive payments, you’ll need to set up one of these options on your profile page.

If you're sponsoring issues, you don't need that until right before making your payment. If you made an offer in USD and you don't have a Paypal account, you'll be prompted to setup one when you're making your first payment (and it's very easy to do so).
```
No different for me.

**Comment by alexarnaud** [comment]
I'm completely OK to do a direct transfer if you've a IBAN.

Best regards,
Alex.

**Comment by raveit65** [comment]
I think everybody have a IBAN, so this might be OK to send it to the guy who fix the issue.
If everybody agree you can simply announce the donation here and we can add a label to issue report.
Eg.
private Donation
In result everybody can see that if he read the report.
@mate-desktop/core-team @mate-desktop/administrators @flexiondotorg 
Is this a way way how we can handle donations?

**Comment by vkareh** [comment]
I don't have access to bank accounts with IBAN, unfortunately, but I'm okay if everybody else defaults to that, and if I want to claim a bounty, I'm okay with paypal, if possible, or to donate it directly to the MATE project.

**Comment by lukefromdc** [comment]
I had to send back the last bounty I got, as not having a Paypal account was worth more than the bounty to mr.

**Comment by raveit65** [comment]
@tamplan 
You should claim the bounty at  https://www.bountysource.com/issues/48917885-pointer-slider-is-not-updatable-with-left-right-arrows

**Comment by tamplan** [comment]
Done.
