### ISSUE TITLE
Natural scrolling is unnatural for "scale" widgets

### ISSUE THREAD

**Issue by rhymoid** [mate-desktop/mate-control-center#305]
#### Expected behaviour

In "natural scrolling", I would expect that scrollbar movement is inverted, but [scale widget](https://developer.gnome.org/gtk3/stable/GtkScale.html) movement is not inverted.

#### Actual behaviour

With natural scrolling, all movement as a result of scrolling is inverted, including the movement of scale widget.

#### Steps to reproduce the behaviour

1. Have a touchpad.
2. In the System menu, go to Preference > Hardware > Mouse.
3. Go to the tab Touchpad.
4. Tick the checkbox "Enable natural scrolling".
5. In the Notification panel item, click on the volume icon.
6. Scroll.

#### MATE general version

1.16.2-2 (the current `mate-desktop` package in stable)

#### Package version

1.16.1-1 (the current `mate-control-center` package in stable)

#### Linux Distribution

Debian stretch

#### Link to downstream report of your Distribution

I have not made a downstream report.

**Comment by rhymoid** [comment]
To be clear, this is what I would expect that natural scrolling entails (assuming horizontal scrolling is disabled):

* Downward gestures:

  * Vertical scale widgets move downwards.
  * Horizontal scale widgets move towards lower values.
  * Pages move so that content disappears at the bottom and appears at the top.

* Upward gestures:

  * Vertical scale widgets move upwards.
  * Horizontal scale widgets move towards higher values.
  * Pages move so that content disappears at the top and appears at the top.

In otherwords: in "natural scrolling", scrollbar movement is inverted, but scale widget movement is not.

**Comment by monsta** [comment]
It was a bug in GTK+3 which affected scales and scrollbars.
See https://bugzilla.gnome.org/788905 and discussion at https://github.com/mate-desktop/caja/issues/855.
