### ISSUE TITLE
Default browser setting is not  come into effect when open html file with double click.

### ISSUE THREAD

**Issue by cxy-uestc** [mate-desktop/mate-control-center#310]
Expected behaviour
There are two browser in mate environment, one is default firefox and the other is chromium;
Set chromium as default application via mate-control-center, then open html file with double click, the browser opened is chromium.

Actual behaviour
The browser opened is still firefox when open html file with double click.

Steps to reproduce the behaviour
1  dnf install crhomium  in Fedora25-MATE
2  Set default browser as chromium
3  Open html file whose suffix is html with double click

MATE general version
1.18.2

Linux Distribution

Fedora-Mate 25

**Comment by cxy-uestc** [comment]
Why?  mate-control-center leave the entry to set mate-default-application, default browser is also included.

**Comment by cxy-uestc** [comment]
Do you means that #150 and #310 is alike?  issue #310 doesn't need to be created?

**Comment by raveit65** [comment]
merged to master and 1.18
c752109f760fd2669ecc210c0cdc98de8c6dc4d7
https://github.com/mate-desktop/mate-control-center/commit/0e75912d87eac43c0af8447aff40049f6dacffef
Thank you
