### ISSUE TITLE
Reinstalling the deleted theme can cause failure

### ISSUE THREAD

**Issue by zhangxianwei8** [mate-desktop/mate-control-center#322]
Expected behaviour
The theme can be installed correctly

Actual behaviour
The theme cannot be installed correctly

Steps to reproduce the behaviour
1. cd /usr/share/themes  (root user)
2. tar zcvf Menta.tar.gz Menta
3. Open m-a-p → "Install..." → choose "/usr/share/themes/Menta.tar.gz"
4. Choose the "Menta" theme to delete
5. Rechoose "/usr/share/themes/Menta.tar.gz" to install again
6. It will be failed with tips: Installation for theme "Menta" failed. Can't move directory over directory

MATE general version
1.19

Package version
1.19.2-1

Linux Distribution
Fedora 27

#### Link to downstream report of your Distribution
N/A

**Comment by zhangxianwei8** [comment]
I find that delete the theme "Menta" just remove theme.index file, when next installing the same theme, the directory /root/.theme/Menta is existed. When move the theme to target directory is failure: https://github.com/mate-desktop/mate-control-center/blob/d2785d62ca9955739a40a61e0e361f0a941e2cd1/capplets/appearance/theme-installer.c#L373

if use G_FILE_COPY_OVERWRITE flag, g_file_move returns always failure:
https://developer.gnome.org/gio/stable/GFile.html#g-file-move
If trying to overwrite a directory with a directory the G_IO_ERROR_WOULD_MERGE error is returned.

So, the g_file_move usage is incorrect.

There is a solution:
Deleting the whole theme directory:
use mate_theme_info_find instead of mate_theme_meta_info_find
https://github.com/mate-desktop/mate-control-center/blob/d2785d62ca9955739a40a61e0e361f0a941e2cd1/capplets/appearance/theme-util.c#L102
@raveit65

**Comment by zhangxianwei8** [comment]
I will commit PR later

**Comment by raveit65** [comment]
I just tested this with a theme which isn't installed under /user/share/themes/
to avoid double thumbnailes.

**Comment by zhangxianwei8** [comment]
Maybe double thumbnailes is a problem. When installing the same theme, there should be a prompt that “The theme is already existed.”

**Comment by raveit65** [comment]
> Maybe double thumbnailes is a problem. When installing the same theme, there should be a prompt that “The theme is already existed.”

Not for me :-)
As a theme artist i like the option to install the same but modified theme in home folder.
But as usual i can copy the theme to ~/.themes if i want.
But maybe it is a good idea to warn a normal user about and ask him if he really want to do that?
“The theme is already existed, do you want to install it again?”

**Comment by zhangxianwei8** [comment]
> But maybe it is a good idea to warn a normal user about and ask him if he really want to do that?
“The theme is already existed, do you want to install it again?”

Yes, this is a good idea to prompt warning information, but if user choose to install the theme, it will fail sometime when ~/.themes/ dir has a same theme. Because if g_file_move use G_FILE_COPY_OVERWRITE flag when move **DIRECTORY** that target is existed(I mentioned above), it always fails. Except deleting the target dir before installation.

**Comment by zhangxianwei8** [comment]
I commit a patch to fix the problem that reinstalling the existed theme causes failure. The solution is that checks the theme dir whether existed. If existed, pop a tips like:
![mshot](https://user-images.githubusercontent.com/33945019/35323998-602a4d0e-012a-11e8-83aa-34f2cd70305f.png)

 Could you please review the code:#326, thanks:) @raveit65 @lukefromdc

**Comment by raveit65** [comment]
Ok, i will test it, but we are in freeze for translations for mate-1.20 release.
So i can merge this only later in feb.
