### ISSUE TITLE
[suggestion] add a way to change appearance via command-line.

### ISSUE THREAD

**Issue by elypter** [mate-desktop/mate-control-center#324]
please add a way to change appearance via command-line. i want to set a cron job that changes between Mint-X and Mint-Y Dark depending on the daytime to get a night mode. it is possible to change the theme but appearance settings change more than just that.

**Comment by elypter** [comment]
this does not change the titlebar, mouse cursors and icons. i am aware of this command.

**Comment by monsta** [comment]
Run `dconf-editor`, proceed to `org > mate > desktop > interface` and find the names of other appearance settings in the list.

**Comment by elypter** [comment]
i could only find the value for icons.

**Comment by flexiondotorg** [comment]
I'm going to close this. As @monsta explained gsettings can be used to change configuration from the terminal, you just have to create a script that does what you need. Finding the keys you want to manipulate is an excise for the reader 😀

**Comment by elypter** [comment]
so why not remove the gui as well if you can just edit config files?

**Comment by alexarnaud** [comment]
Le 21/01/2018 à 11:31, elypter a écrit :
> i could only find the value for icons.

If you have difficulties to figure out you're issue you could contact me 
by mail.

To change the title bar name you need to change 
org.mate.Marco.general.theme for the Marco window manager.

Best regards.
-- 
Alex ARNAUD
Visual-Impairment Project Manager
Hypra - "Humanizing technology"

**Comment by elypter** [comment]
thanks. this depends on the window manager that is currently in use though. i wrote that i want to use this for a night mode but that was not the reason i opened an issue. i think that everything that can be done in a gui should also be doable in command line and vise versa although usually support for the opposite is lacking. separating frontend and backend allows a clean design, otherwise it creates the same problems that windows has. even if i do all the changes individually that is not what the appearance dialog is about. it allows to chose whole style packages. there should be a way to change the appearance as a whole over commandline so that it looks as if i chose it manually over the gui.

**Comment by monsta** [comment]
It's alright to have both ways to do it. It's just that command-line tool already exists.
