### ISSUE TITLE
Feature request: Add buttons-have-icons control to Appearance's Interface tab

### ISSUE THREAD

**Issue by elcste** [mate-desktop/mate-control-center#346]
Ubuntu MATE has icons on buttons by default, but a lot of people like the cleaner look of removing them. Of course you can use `org.mate.interface buttons-have-icons false` [edit: fixed key] (and I do), but this is not is not very discoverable or convenient for a lot of people.

I propose adding this option to the Interface tab of Appearance settings. This would mirror the very similar setting for showing icons on menus that has a control there.

#### Expected behaviour

Have an option in the GUI to control the buttons-have-icons setting so we don't have to use gsettings to change this option.

#### Actual behaviour

No GUI option exists AFAICT. This used to be available in MATE Tweak's Interface section, but that section was removed because the other options are no longer needed.

#### Steps to reproduce the behaviour

N/A

#### MATE general version

1.20.1

#### Package version

1.20.2-2ubuntu1

#### Linux Distribution

Ubuntu MATE Ubuntu 18.04

#### Link to downstream report of your Distribution

https://bugs.launchpad.net/ubuntu/+source/mate-control-center/+bug/1768165

**Comment by lukefromdc** [comment]
You can turn them off in dconf-editor, which can handle most of the gsettings options (I think all of them including the ones in relocatable schemas in the newest versions).

**Comment by elcste** [comment]
True, but I still think it's less discoverable or convenient for a lot of people, and the same kind of option for menu icons is in the settings ;-)

Thanks for your consideration.

**Comment by alexarnaud** [comment]
Le 01/05/2018 à 03:45, lukefromdc a écrit :
> You can turn them off in dconf-editor, which can handle most of the 
> gsettings options (I think all of them including the ones in relocatable 
> schemas in the newest versions).

On the Mate Appearance Property, here Mate 1.16 on Debian, there is an 
interface tab where I can choose to remove icon on menu items.

We could add similar feature for buttons so :).

Best regards,
Alex.

**Comment by raveit65** [comment]
> Of course you can use `gsettings set org.gnome.desktop.interface buttons-have-icons false`

... I am in doubt that this key does have any effect in MATE session :)
```
[rave@mother ~]$ gsettings set org.gnome.desktop.interface buttons-have-icons false
No such key ?buttons-have-icons?
```

Btw. new GUI of dconf-editor looks much better with
dconf-editor-3.28.0-1.fc28.x86_64

**Comment by elcste** [comment]
@raveit65 You are right, I copied the wrong one! It's `gsettings set org.mate.interface buttons-have-icons false`

**Comment by raveit65** [comment]
> On the Mate Appearance Property, here Mate 1.16 on Debian, there is an interface tab where I can choose to remove icon on menu items.

Yes, that would be the right place for it.

**Comment by monsta** [comment]
Yes, we can add it there. This option existed in mintDesktop (of which mate-tweak is a fork) for years, along with "icons in menu items". I'm so used to it that I also thought we had one in appearance properties. :slightly_smiling_face:

**Comment by ericek111** [comment]
@monsta Let's close this one! ^^
