### ISSUE TITLE
How do we install this over existing Mint 18?

### ISSUE THREAD

**Issue by IAMtheIAM** [mate-desktop/mate-control-center#349]
I tried building and installing from source, but it says GTK version incorrect, and no `mate-desktop-2.0` found. But I'm definitely using MATE desktop. Any ideas what to do? I need the rotation fix merged in recently, to solve the gap between my rotated monitors.

**Comment by clefebvre** [comment]
Hi @IAMtheIAM,

Sorry for the delay. We'll have updates in by the end of the month. We're getting delayed because of all the work going on Mint 19 at the moment.
