### ISSUE TITLE
Option to remove icons from buttons

### ISSUE THREAD

**Issue by Ads20000** [mate-desktop/mate-control-center#351]
#### Expected behaviour
MATE Settings (or somewhere else) should provide the option to remove icons from buttons as, allegedly, Xfce does.

#### Actual behaviour
MATE does not provide this option.

#### Steps to reproduce the behaviour
Try to look around MATE to find this option.

#### MATE general version
Probably the current one? This is feedback from [a Disqus comment](https://disqus.com/home/discussion/omgubuntu/gnome_is_removing_the_ability_to_launch_apps_from_nautilus/#comment-3902640523).

#### Package version
Unsure.

#### Linux Distribution
Unsure.

#### Link to downstream report of your Distribution
NA.

#### Screenshot

![](https://uploads.disquscdn.com/images/b79e54008723de363bf35ec687f5a624cfd0a8bbc3e52e7abc96fe4e174e19f9.png)

**Comment by ericek111** [comment]
Already tracked in https://github.com/mate-desktop/mate-control-center/issues/346
