### ISSUE TITLE
Default Applications shows icons at different sizes, causing misalignment

### ISSUE THREAD

**Issue by stuartlangridge** [mate-desktop/mate-control-center#358]
#### Actual behaviour

![sil-1009810219822665728-dgorbd1xuael8-s](https://user-images.githubusercontent.com/4356350/41728388-9e1275e8-756e-11e8-92d5-d9020a340c2f.jpg)

#### Expected behaviour

The dropdown lists should be the same width.

#### Steps to reproduce the behaviour

Open "Preferred Applications".

Whether this problem exhibits is probably dependent on icon themes, but the basic issue is that the icons should be displayed at the same width, regardless. It would be fine I think to display a smaller icon inside an invisible box the width of a larger icon, but the key point is that the dropdown lists not lining up looks ugly.

I think this is fixable in `mate-control-center/master/capplets/default-applications/mate-default-applications-properties.ui` but I'm not sure how best to tell a Gtk Image to always be a certain explicit width and to display the "actual" image centred in that width, or whether there's a better way to solve it.

#### MATE general version

1.20.1.

#### Package version

1.20.2-2ubuntu1

#### Linux Distribution

Ubuntu 18.04.

**Comment by tamplan** [comment]
Hi,

I think i found a solution, making some changes in the code and changing too names ot the icons : 
![Capture du 2019-05-09 23-08-36](https://user-images.githubusercontent.com/50292710/57487176-2b6ec100-72b0-11e9-97f9-8af5dad2d3ae.png)
![Capture du 2019-05-09 23-08-49](https://user-images.githubusercontent.com/50292710/57487177-2b6ec100-72b0-11e9-91e9-a2481ba0311c.png)
![Capture du 2019-05-09 23-12-28](https://user-images.githubusercontent.com/50292710/57487178-2c075780-72b0-11e9-99a1-1ecd8ed62f31.png)
Some icons are missing on some themes...

Without change the names for icons, i plan to purpose a PR tomorrow...

Regards,

**Comment by tamplan** [comment]
Revert names for the icons for the first panel "Internet" : 
![Capture du 2019-05-09 23-34-49](https://user-images.githubusercontent.com/50292710/57488383-3119d600-72b3-11e9-97b9-fc0063ab4b2a.png)
Perhaps we can consider update the mate icons theme...

Regards,
