### ISSUE TITLE
Support AccountService to get/set user icon file.

### ISSUE THREAD

**Issue by yetist** [mate-desktop/mate-control-center#360]
#### Expected behaviour

The user icon displayed by mate-about-me should be the same as lightdm or mate-screensaver.

#### Actual behaviour

The user icon displayed by mate-about-me is different from that of lightdm or mate-screensaver.

#### MATE general version

All versions, include mater branch.

**Comment by monsta** [comment]
I think mate-screensaver should already display the same icon... it's in `~/.face` file.

**Comment by yetist** [comment]
The code merged, close it.
