### ISSUE TITLE
keyboard layout feature does not work

### ISSUE THREAD

**Issue by Safari77** [mate-desktop/mate-control-center#365]
#### Expected behaviour
When I select Finnish, it could actually use Finnish layout and not US.

I have to manually run ```setxkbmap -rules evdev -layout "fi"``` after logging in.

#### Actual behaviour
Layout feature does not work

#### Steps to reproduce the behaviour
Change layout

#### MATE general version
1.21

#### Package version
1.21.0

#### Linux Distribution
Fedora 28

#### Link to downstream report of your Distribution
![mate-keyb-fin](https://user-images.githubusercontent.com/3876865/42927032-776581da-8b33-11e8-8abe-71a26768dca3.png)

**Comment by raveit65** [comment]
I can select the Finnish (classic) layout and can type letters which aren't in my natural keyboard layout.
Typing this letter works in pluma and here with firefox.
![finish-keyboard-layout-1](https://user-images.githubusercontent.com/961604/42928722-64acf654-8b38-11e8-8c82-d13226ae7115.jpg)
![finish-keyboard-layout-2](https://user-images.githubusercontent.com/961604/42928724-64cc6e76-8b38-11e8-8d72-29165d8165db.jpg)
ññññññññññññññññññññññññññññññ

Also the y and z is reversed compare to German layout. Same like with English layout for me.

**Comment by Safari77** [comment]
Cool. Now logoff and login again, does it still work?

**Comment by Safari77** [comment]
I had in ```ibus-setup``` two keyboards configured, but ```control-center``` showed only one keyboard.
I removed US keyboard from ```ibus-setup``` and now I don't have problems in mate.
