### ISSUE TITLE
Login screen disappears when switching displays

### ISSUE THREAD

**Issue by jeenuv** [mate-desktop/mate-control-center#366]
#### Expected behaviour
After suspend or resume, I should be always asked for password in order to use the system.

#### Actual behaviour
if I were to plug an external monitor in (that's configured to become my primary display, and to switch off the laptop display), the log in screen disappears, and I'm able to use the system without requiring my password.

#### Steps to reproduce the behaviour

- Have the display configuration such that external monitor is the primary display, and when it's plugged in, have the laptop display turn off.

- Suspend the laptop, and resume and normal. I'll be taken to the log in screen.

- Plug the monitor external monitor in via. HDMI. Display switches exclusively to the external monitor as configured, but log in screen disappears, and I'm able to use the system without password.

**I'd consider this as a security issue**.

#### MATE general version
1.20

#### Package version
mate-control-center 1.20.2-2ubuntu1

#### Linux Distribution
Linux Mate Tara 64-bit, MATE edition.

I had originally posted it here: https://forums.linuxmint.com/viewtopic.php?f=206&t=273611&p=1499988

**Comment by raveit65** [comment]
Wrong repo. lockscreen is from mate-screensaver and it is already reported, Search for it there.
Sorry, we can't move reports.
