### ISSUE TITLE
Increase set time related applications

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/mate-control-center#405]
@yetist @raveit65 
Do you need to add application related to setup time in mate-control-center?
As shown in the figure：
![image](https://user-images.githubusercontent.com/36913152/50539316-7ae20980-0bb9-11e9-8b4e-675e413924dc.png)
![image](https://user-images.githubusercontent.com/36913152/50539340-f8a61500-0bb9-11e9-892e-388eab92a8b3.png)
![image](https://user-images.githubusercontent.com/36913152/50539343-06f43100-0bba-11e9-9ad1-04889a373482.png)
He can set time, date, time zone and NTP synchronization by calling DBUS interface.

**Comment by lukefromdc** [comment]
The time zone also can be set from the calendar by adding a location and setting it as "home" but nowhere in the clock help is this explained. Ideally the timezone would be configurable directly from clock preferences->time settings, perhaps by a button calling said dialog including in particular the option to enable to disable NTP synchronization. Both enabling AND disabling that can be critical for a laptop used in an environment and role where it is necessary to make no connections to the Internet until Tor and Torbrowser are running and no other connections throughout the session.  

Somewhere in the world, some police agency has probably thought of looking at IP address logs of time servers to attempt to identify where or just exactly when some political dissident booted a laptop away from home. 

Conversely, time skew has also been used in efforts to deanonymize users, and that attack could be used to tie one Tor session to another by an privacy-hostile site like Facebook or by a government agency.  A quick, GUI way to turn this on and off would allow  privacy-sensitive users to sync time at intervals but not connect to timeservers when they are someplace that needs to be deniable.

I have to control this setting from the command line with systemd's timedatectl function, you can see your time zone, whether you have network time enabled, etc on systemd systems with

` sudo timedatectl --monitor`

**Comment by yetist** [comment]
I think there should be a time and date setting application in m-c-c, and it has complete functions, such as setting date, time, time zone, whether to synchronize the time server and so on. The actual function can call `org.freedesktop.timedate1` by dbus.

Now clock applet can set time and date, but can not set time zone and time synchronization,  and new users may not know where to set system time.

**Comment by raveit65** [comment]
To have all i one application might be a good idea.

**Comment by zhuyaliang** [comment]
@lukefromdc I'll give your suggestion serious consideration.
@yetist @raveit65 I'm not quite ready for this time management application. When I'm ready, I'll make a merger request.

**Comment by zhuyaliang** [comment]
Check out the new issues
