### ISSUE TITLE
Turn off Touchpad and set keybind [request]

### ISSUE THREAD

**Issue by DiscipleOfDante** [mate-desktop/mate-control-center#42]
Basically, a lot of users will probably wish they could turn off their touchpad in the control center, and set a keybind to toggle it off and on, some touchpads cause trouble while typing, even with the option to disable touchpad while typing is active. Could this be added?
##

**Comment by matiasdelellis** [comment]
Please,  :+1:

**Comment by mbkma** [comment]
this question is answered here: https://askubuntu.com/questions/639192/how-can-i-set-a-keyboard-shortcut-to-toggle-on-off-e-g-the-trackpad. Just replace `gnome` with `mate` in the script. Btw. MATe has a disable-touchpad-while-typing option.
