### ISSUE TITLE
capplets/display/xrandr-capplet.c snapping uses x,y instead of w,h?

### ISSUE THREAD

**Issue by jm-hi-heg** [mate-desktop/mate-control-center#436]
#### Expected behaviour
Display manager should snap screens together, even when a screen is rotated

#### Actual behaviour
Display manager snaps to a bounding box based on the unrotated screen

#### Steps to reproduce the behaviour
connect two screens
open Display Manager
select the left screen, and choose rotate left
select the right screen, and drag it around the left screen. you will observe it snapping to a bounding box based on an unrotated screen

#### MATE general version
MATE Desktop Environment 1.16.2

#### Package version
mate-control-center-filesystem.x86_64  1.16.1-1.el7                    @epel    
Name        : mate-control-center
Version     : 1.16.1
Release     : 1.el7
Architecture: x86_64
Install Date: Wed 01 May 2019 06:25:39 PM BST
Group       : Unspecified
Size        : 7632136
License     : LGPLv2+ and GPLv2+
Signature   : RSA/SHA256, Sun 05 Feb 2017 02:13:07 PM GMT, Key ID 6a2faea2352c64e5
Source RPM  : mate-control-center-1.16.1-1.el7.src.rpm
Build Date  : Sun 05 Feb 2017 01:57:22 PM GMT
Build Host  : buildvm-22.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://mate-desktop.org
Summary     : MATE Desktop control-center
Description :
MATE Control Center configures system settings such as themes,
keyboards shortcuts, etc.

#### Linux Distribution
Centos 7

**Comment by vkareh** [comment]
@jm-hi-heg, MATE 1.16 is unsupported. Can you test a recent version instead?

I think this issue was resolved with !337

**Comment by jm-hi-heg** [comment]
yes, looks like a duplicate - I did search, but obviously not well enough.

hopefully a newer version will show up in the repo sometime.

**Comment by raveit65** [comment]
> hopefully a newer version will show up in the repo sometime.

Only if you become a fedora packager and start maintaining MATE for epel7 for yourself.
