### ISSUE TITLE
EOM, Firefox (defaults) not detected

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-control-center#443]
#### Expected behaviour
Firefox should show up in "Internet" when installed and set elsewhere as system default(might not work from ff though) and EOM should show up in "Multimedia" as an image viewer when installed

#### Actual behaviour
EOM and Firefox not detected or shown

#### Steps to reproduce the behaviour
Install MATE and Firefox, open mate-control-center default applications

#### MATE general version
1.22/1.23 mix (all available 1.23 versions, mostly current git master)

#### Package version
Locally compiled mate-control-center 1.23.0 from git master current as of 5-10-2019

#### Linux Distribution
Debian Unstable last updated 5-7-2019

#### Link to downstream report of your Distribution
None as this is a locally compiled package (distro did not provide package)

**Comment by monsta** [comment]
@vkareh: reverting https://github.com/mate-desktop/eom/commit/f6d36b99c01aa3cc33bc97b3edb156cc6cf1863f fixes this for eom... looks like these changes to `.desktop` file caused this?

**Comment by monsta** [comment]
@lukefromdc: I can't reproduce the Firefox part in Debian Testing with latest git master of m-c-c. But I'm using Firefox ESR 60.6.3esr-1.

**Comment by lukefromdc** [comment]
Anything Firefox always seems to be buggy at the DE level.

**Comment by rbuj** [comment]
Firefox is shown in Web Browser on Fedora 30 (MIME Type x-scheme-handler/http):
```shell
$ rpm -qi firefox | grep RPM
Source RPM  : firefox-67.0-4.fc30.src.rpm
$ cat /usr/share/applications/firefox.desktop | grep MimeType
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;text/mml;x-scheme-handler/http;x-scheme-handler/https;
```

https://github.com/mate-desktop/mate-control-center/blob/4962557c6f6af249bc3bf8b99baacbed473a16b4/capplets/default-applications/mate-da-capplet.c#L662

![Captura de pantalla a 2019-06-10 20-23-45](https://user-images.githubusercontent.com/10171411/59217364-11314700-8bbe-11e9-9086-c6daa4a5d8d0.png)

**Comment by rbuj** [comment]
Firefox is also shown in Ubuntu 19.10:
```shell
$ firefox -v
Mozilla Firefox 67.0.2
$ cat /usr/share/applications/firefox.desktop | grep MimeType
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
```
Instant Messenger isn't shown on Fedora 30/Ubuntu 19.10.

![Captura de pantalla 2019-06-10 a les 21 00 30](https://user-images.githubusercontent.com/10171411/59219522-fad9ba00-8bc2-11e9-8ee2-186e226b9c7d.png)

test:
```shell
$ sudo apt-get install -y hexchat pidgin
$ sudo update-desktop-database
$ LANG=C mate-default-applications-properties
```

**Comment by lukefromdc** [comment]
I now get the EOM icon but NOT eom itslelf showing up. Firefox is also still a no-show but my results there can probably be ignored as I have a very nonstandard install.

**Comment by lukefromdc** [comment]
I can confirm EOM now shows up in the default applications. As I have a modified firefox in /usr/local this probably isn't going to show up and can be disregarded. Fine that this has been closed
