### ISSUE TITLE
Added new time and date management services

### ISSUE THREAD

**Issue by zhuyaliang** [mate-desktop/mate-control-center#449]
@raveit65 @yetist 
I wrote a new time and date management service, which I want to add to mate component. How do you like it?He's not perfect yet. If you agree with this idea, I'll continue to optimize the service.
https://github.com/zhuyaliang/time-admin

**Comment by flexiondotorg** [comment]
I love that you're working on `user-admin` and `time-admin` 🙂 

Ubuntu MATE ships the old `gnome-system-tools` to provide user and time configuration but having some in MATE itself would be preferable in my opinion 👍

**Comment by yetist** [comment]
Time and date management is available in the clock applet, but not in M-c-c, it would be better if we could provide it in the control center.
You can also modify the clock applet and call time-admin directly.
