### ISSUE TITLE
General questions about GUI

### ISSUE THREAD

**Issue by tamplan** [mate-desktop/mate-control-center#464]
I would like to resolve this issue https://github.com/mate-desktop/mate-control-center/issues/377 and note that m-c-c does not have too a close button like other 'capplet' or mate-panel applets.

I code a little function which adds a header_bar with two icons (and two tooltips) only passing GtkWindow of the application as parameter to be used for others applications in Mate Desktop for example.

The function manage yet the window's buttons layout choice between left or right.

The result should be for m-c-c like that:
![m-c-c-1](https://user-images.githubusercontent.com/50292710/59566120-da46af80-905b-11e9-90de-acdb468ec0d2.png)

Or another function (unfinished for the moment) i wrote with only a menu without icon (due to limitation or my ignorance about GTK 3) like this:
![m-c-c-2](https://user-images.githubusercontent.com/50292710/59566132-0a8e4e00-905c-11e9-810d-00d36c42ea04.png)

And to finish, a capplet or mate-panel applet can use the same design:
![desktop-icons](https://user-images.githubusercontent.com/50292710/59566140-298ce000-905c-11e9-8f65-2444c8ff57b9.png)
Or the second with menu.

You can imagine automatically toggle between the two modes when a user wants to use icons in the menus or not for example.

It should be more aesthetic and professional if all application have the same design (specially those have no menu bar), a way to launch help and display a about box.

What do you think about that?

**Comment by lukefromdc** [comment]
This follows the GNOME rather than the MATE design principles

**Comment by tamplan** [comment]
Ok, in that case, we should do the opposite, add a Help button and a Close button (for example not shown in the Desktop icons app).

What about a about dialog box for all applications or applets of mate-panel?

Regards

**Comment by raveit65** [comment]
I don't like to use headerbars.

**Comment by tamplan** [comment]
Me too, a title bar is a title bar and nothing else.

I"m not waste my time practice programming in C for learning even if it's not reverse in a PR.

Thanks for explanations.

Regards

**Comment by lukefromdc** [comment]
No, such practice is never a waste at all, is the skills can be reused over and over. Also no reason in the world for you not to enjoy a modified version of any FOSS programs done to suit your personal tastes, and in fact this sort of thing is a great way to learn programming. This in fact is exactly how I learned to work with C and GTK3.

**Comment by mbkma** [comment]
If you have suggestions for new developers you can also add them to the wiki https://wiki.mate-desktop.org/.
