### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by tamplan** [mate-desktop/mate-control-center#470]
#### Expected behaviour
To compile the code

#### Actual behaviour
Got a message: "Package 'mate-desktop-2.0' has version '1.22.1', required version is '>= 1.23.1'" with mate-about -v displaying me 1.23.1
mate-desktop repository master branch seems to be installed but got 1.22.1 in system monitor.

#### Steps to reproduce the behaviour
Launch ./autogen.sh

#### MATE general version
1.23 (master)

#### Package version
1.23 (master)

#### Linux Distribution
Fedora 30 x86_64

#### Link to downstream report of your Distribution
none

Thank by advance!

**Comment by tamplan** [comment]
Switch back to Ubuntu 19.04 and i have the same issue:

> checking for GSD_DBUS... no
configure: error: Package requirements (mate-settings-daemon >= 1.23.0) were not met:
> Requested 'mate-settings-daemon >= 1.23.0' but version of mate-settings-daemon is 1.22.0
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
> Alternatively, you may set the environment variables GSD_DBUS_CFLAGS
and GSD_DBUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more 

mate-settings-daemon 1.23 is compiled and installed.

**Comment by raveit65** [comment]
> mate-settings-daemon 1.23 is compiled and installed

How did you install mate-settings-daemon-1.23 ?
Did you uninstall mate-settings-daemon version from package-manager?
Are you sure have not 2 versions installed?

**Comment by raveit65** [comment]
In f30 what is the result of `rpm -qa mate-settings-daemon` ?

**Comment by tamplan** [comment]
i have not think to remove mate-settings-daemon version from package-manager because his removal remove too other package nut i will try your solution.

Sorry about fedora i switch back to ubuntu and can't test your command line tool.

**Comment by tamplan** [comment]
removing mate-settings-daemon remove mate-desktop-environment-core that contents /usr/share/glib-2.0/schemas/10_mate-common.gschema.override, i must to try and investigate.

Thanks for help.

**Comment by tamplan** [comment]
Uninstall the mate-settings-daemon package, compile and install it (make install) don't resolve this issue.

mate-control-center don't "see" mate-settings-daemon 1.23 installed...

**Comment by vkareh** [comment]
What configure flags are you using? You should be using `--prefix=/usr`, and make sure you don't have remnants of an old build inside `/usr/local/`

**Comment by tamplan** [comment]
I just use "/autogen.sh" with no flag, every time with no issue.

I'll try your suggestion removing old build inside /usr/local/...

**Comment by tamplan** [comment]
i have this:
`tamplan@TV:/usr/local/bin$ ls -al
total 22832
drwxr-xr-x  2 root root     4096 juin  24 22:07 .
drwxr-xr-x 11 root root     4096 juin  23 15:40 ..
-rwxr-xr-x  1 root root 10760544 juin  24 21:14 caja
-rwxr-xr-x  1 root root   104128 juin  24 21:14 caja-autorun-software
-rwxr-xr-x  1 root root  3047888 juin  24 21:14 caja-connect-server
-rwxr-xr-x  1 root root  2997144 juin  24 21:14 caja-file-management-properties
-rwxr-xr-x  1 root root    91944 juin  24 21:24 caja-sendto
-rwxr-xr-x  1 root root    63104 juin  23 15:01 mate-about
-rwxr-xr-x  1 root root    34184 juin  23 15:01 mate-color-select
-rwxr-xr-x  1 root root   527192 juin  23 21:42 mate-desktop-item-edit
-rwxr-xr-x  1 root root  3353832 juin  23 21:42 mate-panel
-rwxr-xr-x  1 root root   264888 juin  23 21:42 mate-panel-test-applets
-rwxr-xr-x  1 root root   815848 juin  23 22:28 mate-screensaver
-rwxr-xr-x  1 root root    50920 juin  23 22:28 mate-screensaver-command
-rwxr-xr-x  1 root root   302976 juin  23 22:28 mate-screensaver-preferences
-rwxr-xr-x  1 root root   675544 juin  24 22:07 mate-volume-control
-rwxr-xr-x  1 root root   251432 juin  24 22:07 mate-volume-control-status-icon`

All is done with ''./autogen.sh, make, sudo make install" without prefix.

I have too:
`tamplan@TV:/usr/local/libexec$ ls -la
total 3608
drwxr-xr-x  3 root root    4096 juin  25 19:07 .
drwxr-xr-x 11 root root    4096 juin  23 15:40 ..
-rwxr-xr-x  1 root root  753976 juin  23 21:42 clock-applet
-rwxr-xr-x  1 root root  193824 juin  23 21:42 fish-applet
drwxr-xr-x  2 root root    4096 juin  23 22:28 mate-screensaver
-rwxr-xr-x  1 root root  315104 juin  23 22:28 mate-screensaver-dialog
-rwxr-xr-x  1 root root   37616 juin  23 22:28 mate-screensaver-gl-helper
-rwxr-xr-x  1 root root  183728 juin  25 19:07 mate-settings-daemon
-rwxr-xr-x  1 root root  278008 juin  24 22:07 mate-volume-control-applet
-rwxr-xr-x  1 root root  158080 juin  25 19:07 msd-datetime-mechanism
-rwxr-xr-x  1 root root  141976 juin  25 19:07 msd-locate-pointer
-rwxr-xr-x  1 root root 1345056 juin  23 21:43 notification-area-applet
-rwxr-xr-x  1 root root  254488 juin  23 21:43 wnck-applet`

and suppose i need to remove 'mate-settings-daemon'

**Comment by tamplan** [comment]
i have just compile and install mate-settings-daemon downloaded from https://github.com/mate-desktop/mate-settings-daemon/releases/tag/v1.23.0 with no result.

**Comment by tamplan** [comment]
Sorry, my mate-settings-daemon local repository was unclear and was not the same than his remote copy, just delete and fork again the original repository solve this issue...
