### ISSUE TITLE
[Request] Add additional mouse settings for disabling mouse acceleration and middle click emulation [$350]

### ISSUE THREAD

**Issue by heew** [mate-desktop/mate-control-center#491]
As was done in Gnome 3.22 (see https://www.reddit.com/r/linux_gaming/comments/553v1p/gnome_322_includes_option_to_disable_mouse/) we should be able to disable these settings from the GUI and not be forced to use xinput --list and xinput --set-prop.

It really is not good for gaming to have mouse acceleration and I cannot get X to respect any of my .conf files to this (even after following the "man xorg.conf.d").

Image here shows how Gnome has it in the GUI: https://imgur.com/a/DYdUO.

I am currently working around this with a self-made script that I run prior to gaming, but I feel this should be more easier to work around.

Keep up the great work with MATE and I hope we can make it better!

**Comment by vkareh** [comment]
I've submitted several patches to fix this. All three are needed for this to work:
* https://github.com/mate-desktop/mate-desktop/pull/407
* https://github.com/mate-desktop/mate-settings-daemon/pull/293
* https://github.com/mate-desktop/mate-control-center/pull/494
