### ISSUE TITLE
applications which needed pkexec doesn't start from m-c-c window

### ISSUE THREAD

**Issue by NiceandGently** [mate-desktop/mate-control-center#51]
This relates application wo needs pkexec, they start well from a terminal but not from m-c-c window.
i.e for fedora, system-config-date or system-config user.
Starting m-c-c from a terminal shows me this output.
'Refusing to render service to dead parents.'

For mate-panel i fixed this already with this commit.
https://github.com/mate-desktop/mate-panel/commit/2905402c0b856eaf86e497c41bbe0d630647c6f6
what has closed this issue
https://github.com/mate-desktop/mate-polkit/issues/2

Unfortunately, i don't know how to do this in libslab.

**Comment by monsta** [comment]
Do you still experience this in 1.8.x?
In Mint 17.1 Rebecca with m-c-c 1.8.3, I can run synaptic-pkexec from m-c-c just fine.

Unfortunately, Debian and Ubuntu don't have Fedora's system-config-* tools (except for system-config-printer I think), so I can't use them for testing.

**Comment by NiceandGently** [comment]
Yes, it seems the issue ocours if apps use 'exec' in the script. See
https://bugzilla.redhat.com/show_bug.cgi?id=972534#c6
After removing the exec command from the start scripts the application starts well.
I don't know really if an 'exec' command is really neded in a script and i filled out reports against those apps, but i got no reply yet.
It should be possible to reproduce this with a simple script which call a 'root' application.

**Comment by monsta** [comment]
This "exec" seems to be excessive...

**Comment by NiceandGently** [comment]
@tarakbumba 
The real issue is identified, see https://bugzilla.redhat.com/show_bug.cgi?id=972534#c6
Removing 'exec' from the command line of this apps fixes it.

**Comment by tarakbumba** [comment]
@NiceandGently, unfortunately this is not a fix but a workaround. We can not expect every utility/application developer to remove exec line from their wrapper scripts. Note that, not all of this kind utiliy use a wrapper script like https://bugzilla.redhat.com/show_bug.cgi?id=972534#c6. Some needs to be run via pkexec directly from .desktop file.

**Comment by NiceandGently** [comment]
@monsta 
This is reproducible in jessie when you edit /usr/bin/synaptic-pkexec.
Edit
```
#!/bin/sh
pkexec "/usr/sbin/synaptic" "$@"
```
to
```
#!/bin/sh
exec pkexec "/usr/sbin/synaptic" "$@"
```
Now synaptic starts well from menu but not anymore from mate-control-center.
Note, for mate-panel i fixed this with https://github.com/mate-desktop/mate-panel/commit/2905402c0b856eaf86e497c41bbe0d630647c6f6
but i don't know to do this in m-c-c.
I'm quessing the code must be add somewhere in app-resizer.c or another file inside /libslab folder.

**Comment by monsta** [comment]
Yes, I confirm that. After the mentioned change, Synaptic doesn't start from m-c-c anymore, and in the terminal I get this:

```Refusing to render service to dead parents.```

I'll look at the code but can't promise anything because this time the upstream is of no help for us: the code in g-c-c is quite different...

**Comment by NiceandGently** [comment]
yes, this is exactly the so called 'double forking' issue.
Maybe, it's possible to do the same what i did for mate-panel.
Anyways, i culprit package is fixed in fedora, 2 are left.
https://bugzilla.redhat.com/show_bug.cgi?id=1185860

**Comment by NiceandGently** [comment]
system-config-language and system-config-keyboard is fixed now in fedora.
https://bugzilla.redhat.com/show_bug.cgi?id=1185861#c11
https://bugzilla.redhat.com/show_bug.cgi?id=1185860
so, we have only one left over

**Comment by monsta** [comment]
@tarakbumba: https://github.com/mate-desktop/mate-desktop/pull/166 and https://github.com/mate-desktop/mate-control-center/pull/152 should fix it. Please test and tell me if you see something wrong both in the code and in the runtime. :)

**Comment by NiceandGently** [comment]
confirmed, that fixes the issue.

**Comment by tarakbumba** [comment]
Confirmed. These two commits fixes this issue, thank you @monsta. I think these commits should go both to 1.8 branch and to master (upcoming 1.10)

**Comment by NiceandGently** [comment]
updates submitted https://bugzilla.redhat.com/show_bug.cgi?id=972534#c10
