### ISSUE TITLE
Regression: Windows control widget disfunct in German localization

### ISSUE THREAD

**Issue by Megatokio** [mate-desktop/mate-control-center#510]
when clicking on "Fenster" [Window] in "Kontrollzentrum" (control center) 

#### Expected behaviour
expected any kind of windows settings to open

#### Actual behaviour
error popup: "Die aktuelle Fensterverwaltung wird nicht unterstützt"

#### Steps to reproduce the behaviour
click on "Fenster" [Window] in "Kontrollzentrum" (control center) 

#### MATE general version
1.22.2

#### Package version
??

#### Linux Distribution
Ubuntu 19.10 64bit

#### Link to downstream report of your Distribution
??

**Comment by sc0w** [comment]
it seems not related to the language, I can't reproduce this issue, I think it needs more info

my tests:

- $ env LANG=de_DE.UTF-8 mate-control-center

- click in `Fenster`

it works fine

**Comment by Megatokio** [comment]
Confirmed, it also happens with English language.
If helpful info is logged, i need info which logfile to look in.
i have installed Mate Tweaks and there is a tab "Windows" too which works. Eventually it displays just exactly the same widget. (at least i found heer what i was looking for)
I also installed CCSM and i updated to Linux 5.3 recently.

**Comment by mbkma** [comment]
which window manager do you use?

**Comment by Megatokio** [comment]
I think i was using Compiz, but no longer 100% sure. I switched to Mint later and therefore i cannot tell whether this problem persisted or changed meanwhile. Since noone elese showed interest in this issue it's probably best to close it.
Thanks for your effort anyway. ;-)

**Comment by mbkma** [comment]
yeah, compiz has an extra control panel, so it makes sense that you got this error message :)
