### ISSUE TITLE
Blurred icons on HiDPI display

### ISSUE THREAD

**Issue by damour** [mate-desktop/mate-control-center#529]
#### Expected behaviour
Icons are crisp

#### Actual behaviour
Icons are blurred

#### Steps to reproduce the behaviour
Open mate-control-center

#### MATE general version
1.22.2

#### Package version
1.22.2-1+tricia

#### Linux Distribution
Mint mate 19.3

![Центр управления_036](https://user-images.githubusercontent.com/881794/72224071-e60d3c80-357e-11ea-9294-27d4b50b9d3d.png)

**Comment by vkareh** [comment]
Fixed by https://github.com/mate-desktop/mate-control-center/commit/a4878c0dc05ca67ee8c20dbd3039e5d9e8c99df0
