### ISSUE TITLE
mate-control-center fails to start

### ISSUE THREAD

**Issue by DidierSpaier** [mate-desktop/mate-control-center#554]
#### Expected behavior
Typing mate-control-center should start it.

#### Actual behavior
I get this output:

idier[~]$ mate-control-center 

** (mate-control-center:5307): WARNING **: 19:53:42.607: 
error raised: [load_xbel_store: couldn't load bookmark file [NULL]
]

**
ERROR:app-shell.c:1328:application_launcher_compare: code should not be reached
Bail out! ERROR:app-shell.c:1328:application_launcher_compare: code should not be reached
Abandon

#### Steps to reproduce the behavior
See above

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Slint 14.2 

#### Link to downstream report of your Distribution
Version not yet shipped (I am the Slint maintainer)

However, included other binaries start normally from mate-terminal.

glib2-2.62.3 is installed.

[configure.log](https://github.com/mate-desktop/mate-control-center/files/4331214/configure.log)

[debug.log](https://github.com/mate-desktop/mate-control-center/files/4331198/debug.log)

**Comment by raveit65** [comment]
> ** (mate-control-center:5307): WARNING **: 19:53:42.607:
error raised: [load_xbel_store: couldn't load bookmark file [NULL]

This one i an old harmless warning, i see them since years.

Can you try to build without `--enable-maintainer-mode`. I never did that for fedora
And what is `mate-doc-common`?
```
(B[m  testing mate-doc-common... found 1.24.0
```
These are my build options for fedora https://src.fedoraproject.org/rpms/mate-control-center/blob/master/f/mate-control-center.spec#_94

**Comment by DidierSpaier** [comment]
No luck, same error message. As an aside, I didn't write '--enable-maintainer-mode', autogen.sh did it. And ./configure --help does not mention this option.

I attach the relevant part of the build script I just used and the corresponding configure log.
Indeed mate-doc-common is a binary shipped in mate-common. Why it is tested when running  autogen.sh, I don't know.

Thanks.

[build2.txt](https://github.com/mate-desktop/mate-control-center/files/4331773/build2.txt)
[configure2.log](https://github.com/mate-desktop/mate-control-center/files/4331774/configure2.log)

**Comment by DidierSpaier** [comment]
Meanwhile reverting mate-power-manager from 1.24.0 to 1.22.2 allowed mate-control-center 1.22.2 as well as 1.24.0 to start. No idea why. I have installed upower 0.99.11 if that matters.
