### ISSUE TITLE
What is the /org/mate/desktop/background/draw-background key?

### ISSUE THREAD

**Issue by tamplan** [mate-desktop/mate-control-center#567]
Hi,
I don't know where to post this question.

Can someone explain me why the /org/mate/desktop/background/draw-background key exist? And what is he function?

Is there a case where the background is not drawn?

Thanks by advance
Regards

**Comment by raveit65** [comment]
With this key m-s-d draw the desktop when caja doesn't draw icons + background.

**Comment by tamplan** [comment]
So, the background (the image) is always drawn:
- by Caja when the key is FALSE
- by m-s-d when the key is TRUE

In any case, the desktop page from m-c-c appearance capplet is always showed?

Is it right?

Thanks by advance.
Regards

**Comment by raveit65** [comment]
```
[rave@mother ~]$ gsettings get org.mate.background draw-background
true
[rave@mother ~]$ gsettings get org.mate.background show-desktop-icons
true
[rave@mother ~]$
```
If both keys are `false` than you have a black desktop.
 `org.mate.background show-desktop-icons` is always prioritized.
When `org.mate.background show-desktop-icons` is  `true` it doesn't matter if `org.mate.background draw-background is set to true or false.

Honestly, i never tested if m-c-c shows the desktop page in this case :)
Try it out.

**Comment by tamplan** [comment]
Where the 2 keys you mention are FALSE, the m-c-c shows the desktop page...

Let's go for a future PR...

Thanks you very much!

**Comment by raveit65** [comment]
Please close topic!
