### ISSUE TITLE
[Feature Request] Add a scale option in Display settings.

### ISSUE THREAD

**Issue by Neverest** [mate-desktop/mate-control-center#595]
#### Expected behaviour
An option in the Display GUI to set the scaling. 

#### Actual behaviour
No scaling option in the Display GUI. I know there is an option in Mate-Tweak, but it would be nice to have it with all the other monitor options like the other desktop environment such as: [gnome3](https://149366088.v2.pressablecdn.com/wp-content/uploads/2017/09/Screen-Shot-2017-09-22-at-00.39.31.png), [cinnamon ](https://149366088.v2.pressablecdn.com/wp-content/uploads/2020/02/cinnamon-refresh-rate-monitor.png)& [xfce4](https://149366088.v2.pressablecdn.com/wp-content/uploads/2020/09/xfce-4.16.jpg).

#### Steps to reproduce the behaviour
Just go to the Display GUI.

#### MATE general version
1.24

#### Package version
1.24.1-1

#### Linux Distribution
Ubuntu Mate 20.04LTS

**Comment by mbkma** [comment]
done, see https://github.com/mate-desktop/mate-control-center/commit/1cca4936a347ad4c7c81e18fcf913e6b393a2994
