### ISSUE TITLE
Commit 844db92 (appearance: Add file chooser settings - Nov 29, 2020) breaks Mate Control Center if GTK3 < 3.24.12

### ISSUE THREAD

**Issue by L-U-T-i** [mate-desktop/mate-control-center#637]
#### Expected behaviour
Mate Control Center launch, and is usable as expected

#### Actual behaviour
Mate Control Center (as well as Appearance Properties binary) does not launch on CentOS 8.3 at all, the following is thrown out if launched from terminal:
(mate-appearance-properties): GLib-GIO-ERROR **: Settings schema 'org.gtk.Settings.FileChooser' does not contain a key named 'show-type-column'

#### Steps to reproduce the behaviour
launch 'mate-control-center' binary or 'mate-appearance-properties' binary from a terminal on any system with gtk3 version less than 3.24.12

#### MATE general version
1.25.1 (git commits after 844db92, by today)

#### Package version
Custom build on CentOS 8.3 / SPEC file based on Fedora 1.24 SRPM

#### Linux Distribution
CentOS 8

#### Link to bugreport of your Distribution (requirement)
-

As much as I've been able to find, [commit 844db921aeed3e987f3be0f4e7e0b3a9703612ac](https://github.com/mate-desktop/mate-control-center/commit/844db921aeed3e987f3be0f4e7e0b3a9703612ac) introduced "File Chooser" settings (in Appearance Preferences / Interface tab), among which "Show type column" checkbox / setting is not available in GTK3 before 3.24.12.

I've created a patch which fixes the crash:
[patch-1.diff.txt](https://github.com/mate-desktop/mate-control-center/files/6198277/patch-1.diff.txt)

With this patch, I was able to launch both mate-control-center and mate-appearance-properties, but the problematic setting was still available (even if not useful), what could be misleading.

I've therfore added a patch for glade appearance.ui file, which shall be applied conditionally (if gtk3 < 3.24.12 only - to inactivate / grey out this checkbox / setting):
[patch-2.diff.txt](https://github.com/mate-desktop/mate-control-center/files/6198278/patch-2.diff.txt)

It would maybe be better to inactivate / grey out this checkbox / setting at runtime (if gtk3 < 3.24.12 / setting not available), or hide it, but I don't want to mess with the code more than really necessary (and, I feel to be safe - I'm not a coding expert at all...).

**Comment by rbuj** [comment]
Please, can you send a PR?
```diff
diff --git a/capplets/appearance/appearance-main.c b/capplets/appearance/appearance-main.c
index 8798319..03dbff8 100644
--- a/capplets/appearance/appearance-main.c
+++ b/capplets/appearance/appearance-main.c
@@ -190,6 +190,10 @@ main (int argc, char **argv)
   capplet_set_icon (w, "preferences-desktop-theme");
   gtk_widget_show_all (w);
 
+#if !GTK_CHECK_VERSION(3, 24, 12)
+  gtk_widget_hide (GTK_WIDGET (gtk_builder_get_object (data->ui, "filechooser_type_column_toggle")));
+#endif /* !GTK_CHECK_VERSION(3, 24, 12) */
+
   g_signal_connect_after (w, "response",
                           (GCallback) main_window_response, data);
 
diff --git a/capplets/appearance/appearance-ui.c b/capplets/appearance/appearance-ui.c
index 8b21056..5b0437d 100644
--- a/capplets/appearance/appearance-ui.c
+++ b/capplets/appearance/appearance-ui.c
@@ -114,11 +114,13 @@ ui_init (AppearanceData *data)
                      "active",
                      G_SETTINGS_BIND_DEFAULT);
 
+#if GTK_CHECK_VERSION(3, 24, 12)
     g_settings_bind (data->filechooser_settings,
                      FILECHOOSER_TYPE_COL_KEY,
                      gtk_builder_get_object (data->ui, "filechooser_type_column_toggle"),
                      "active",
                      G_SETTINGS_BIND_DEFAULT);
+#endif /* GTK_CHECK_VERSION(3, 24, 12) */
 
     g_settings_bind (data->filechooser_settings,
                      FILECHOOSER_DIR_FIRST_KEY,
diff --git a/capplets/appearance/appearance.h b/capplets/appearance/appearance.h
index b92cf19..4aa7cb1 100644
--- a/capplets/appearance/appearance.h
+++ b/capplets/appearance/appearance.h
@@ -49,7 +49,9 @@
 #define FILECHOOSER_DIR_FIRST_KEY    "sort-directories-first"
 #define FILECHOOSER_HIDDEN_ITEMS_KEY "show-hidden"
 #define FILECHOOSER_SIZE_COL_KEY     "show-size-column"
+#if GTK_CHECK_VERSION(3, 24, 12)
 #define FILECHOOSER_TYPE_COL_KEY     "show-type-column"
+#endif /* GTK_CHECK_VERSION(3, 24, 12) */
 #define GTK_FONT_DEFAULT_VALUE       "Sans 10"
 #define GTK_FONT_KEY                 "font-name"
 #define GTK_THEME_KEY                "gtk-theme"
```
https://github.com/GNOME/gtk/commit/c925221aa804aec344bdfec148a17d23299b6c59
