### ISSUE TITLE
Arabic Mate control center must have RTL titles .

### ISSUE THREAD

**Issue by moceap** [mate-desktop/mate-control-center#65]
Secondary titles in MATE control center must be RTL align , when run it in Arabic session.

![cc](https://f.cloud.github.com/assets/4345211/906263/255f4f5c-fc85-11e2-99e4-88ef7a7aa3c4.png)
##

**Comment by tamplan** [comment]
#136 to see screenshots if not resolved.

**Comment by moceap** [comment]
![w](https://user-images.githubusercontent.com/4345211/94773823-39514480-03c5-11eb-90b2-5c95e8bf5bfe.png)

Fixed
