### ISSUE TITLE
Add ability to change device (net) name and username

### ISSUE THREAD

**Issue by Porrumentzio** [mate-desktop/mate-control-center#656]
#### Expected behaviour
I would expect that in Control Center, in the section "Personal data", both username and its alias and device's net name (`username@device` in terminal, for example) could be changed.

#### Actual behaviour
Currently only image and password can be changed. Username and alias appear but are not editable, and device name does not even appear.

#### Steps to reproduce the behaviour
Control Center > Personal > Personal data

#### MATE general version
1.26

#### Package version
1.26

#### Linux Distribution
Manjaro Linux MATE

#### Link to bugreport of your Distribution (requirement)
https://manjaro.org/

**Comment by zhuyaliang** [comment]
You can try it [mate-user-admin]( https://github.com/zhuyaliang/user-admin)

**Comment by zhuyaliang** [comment]
@Porrumentzio Whether the problem has been solved

**Comment by Porrumentzio** [comment]
Sorry for the late answer. I don't use MATE anymore, so I cannot test the change. Anyway, I trust you, so you can close this issue.

**Comment by zhuyaliang** [comment]
Thank you for your reply. I will close this issue
