### ISSUE TITLE
Two strings that shouldn't be marked for gettext.

### ISSUE THREAD

**Issue by yarons** [mate-desktop/mate-control-center#660]
https://github.com/mate-desktop/mate-control-center/blob/master/capplets/time-admin/src/main.c#L264
https://github.com/mate-desktop/mate-control-center/blob/master/capplets/time-admin/src/main.c#L277

These two shouldn't be marked as gettext because there's no comprehensible way to transalate them to different language without completely losing the context.

I can prepare a quick patch for it.

**Comment by raveit65** [comment]
A quick patch would be nice.

**Comment by yarons** [comment]
Done #663

**Comment by raveit65** [comment]
Resources are updated for transifex.
https://github.com/mate-desktop/mate-control-center/commit/5e6f1ebd8c4eff1ff94611c49c7612b066471f46
https://github.com/mate-desktop/mate-control-center/commit/a8b1848e76518629928d6314b44fca415483b90d
Change s should be available after next pull from transifex.
