### ISSUE TITLE
mate-font-viewer shows  Gtk-CRITICAL messages in terminal

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mate-control-center#671]
#### Expected behaviour
font(s) is/are found, the terminal is empty

#### Actual behaviour
font(s) is/are found, but terminal has Gtk critical messages like

```
(mate-font-viewer:21717): Gtk-CRITICAL **: 18:57:01.681: gtk_tree_model_filter_real_unref_node: assertion 'elt->ref_count > 0' failed
```

#### Steps to reproduce the behaviour
1. Install Ubuntu MATE 21.10
2. Launch `mate-font-viewer` from the terminal
3. Wait `mate-font-viewer` to load all fonts

#### MATE general version
1.26.0

#### Package version
1.26.0-0ubuntu1

#### Linux Distribution
Ubuntu MATE 21.10

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/+source/mate-control-center/+bug/1863429

**Comment by N0rbert** [comment]
Still happens  on latest Ubuntu MATE 22.04 LTS beta.

**Comment by lukefromdc** [comment]
I was just unable to duplicate this on Debian Unstable (no doubt w different installed fonts though).  Got a clean run from terminal w no messages or warnings shown

**Comment by zhuyaliang** [comment]
No bad output
```
@test-pc:~/work/project/accountsservice-22.07.5$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
test@test-pc:~/work/project/accountsservice-22.07.5$ mate-font-viewer 

```

**Comment by N0rbert** [comment]
I can't reproduce on daily driver Debian 11 and on upcoming Debian 12.
