### ISSUE TITLE
Unlocalised string "Printers".

### ISSUE THREAD

**Issue by Mejans** [mate-desktop/mate-control-center#693]
Hello,
I notice that in the Administration section the entry "Printers" is not localised into Occitan, oc.
I cannot find "printers" in the po file.
On hover, I have the value of Comment from the Desktop Entry, so I find it strange that Name is not used.

**Comment by zhuyaliang** [comment]
The ```Printers``` is not supplied by ```mate-c-c```

**Comment by Mejans** [comment]
Hello @zhuyaliang where does this string come from?

**Comment by zhuyaliang** [comment]
Probably ```gnome-control-center```
Run ```grep -rin Printers /usr/share/applications/``` to see which file provides this string

**Comment by Mejans** [comment]
Hello,
on Ubuntu MATE the output of the command is:
https://i.ibb.co/9pf5NHB/sortida.png
So it comes from system-config-printer.desktop.
But at least in the previous LTS (focal) it was already translated in system-config-printer and it still is.
I've tried in Catalan and French and this entry in Control Centre is not translated.

**Comment by zhuyaliang** [comment]
This is an incomplete desktop file, missing the translation part

**Comment by Mejans** [comment]
This is a Ubuntu only bug, sorry for the trouble!
