### ISSUE TITLE
Screensaver icon not used from icon theme

### ISSUE THREAD

**Issue by varlesh** [mate-desktop/mate-control-center#695]
#### Expected behaviour

Screensaver icon `preferences-desktop-screensaver` not applied from current icon theme. On DEBUG it's used from Humanity icon theme. Destktop launcher show correctly icon.

![Снимок экрана в 2022-07-05 07-03-43](https://user-images.githubusercontent.com/8083855/177271414-641c77ef-1c89-4aef-a198-5c3b5476cf7c.png)

#### Actual behaviour

Screensaver icon used from current icon theme

#### Steps to reproduce the behaviour

- Install eny icon theme with `preferences-desktop-screensaver` icon (Papirus, for example)
- set new icon theme on settings
- restart mate-control-center

#### MATE general version

1.26.0

#### Package version

1.26.0-2ubuntu3

#### Linux Distribution

Ubuntu Mate 22.04

**Comment by raveit65** [comment]
You're using ubuntu themes. Please file out a report there.
