### ISSUE TITLE
mate-user-admin Switch Bug

### ISSUE THREAD

**Issue by Khayasen** [mate-desktop/mate-control-center#700]
#### Expected behaviour
The automatic logon appears like a normal switch

#### Actual behaviour
The switch looks stretched and enlarged

#### Steps to reproduce the behaviour
run mate-user-admin

#### MATE general version
Mate 1.26.0

#### Package version
Can't find the way to find it.

#### Linux Distribution
Ubuntu Mate (Kinetic Kudu) 22.10

#### Link to bugreport of your Distribution (requirement)

![Screenshot at 2022-11-11 12-39-40](https://user-images.githubusercontent.com/103806906/201272067-3c1e14d2-4376-4671-ab11-0cde08602bba.png)

**Comment by mbkma** [comment]
This is not a program of MATE-Desktop, please file your bug here: https://github.com/zhuyaliang/user-admin.
