### ISSUE TITLE
Please migrate to from Ubuntu Indicators to Ayatana Indicators

### ISSUE THREAD

**Issue by pacho2** [mate-desktop/mate-control-center#701]
libayatana-appindicator and dev-libs/libayatana-indicator are the only appindicators implementation that are still maintained and developped, while Ubuntu libappindicator stuff are unmaintained for ages.

OpenSUSE and Debian already migrated:
https://wiki.debian.org/Ayatana/IndicatorsTransition

Thanks

**Comment by raveit65** [comment]
Fedora and Redhat are using libappindicator and not libayatana-indicator. It is important that we can use both packages.

**Comment by pacho2** [comment]
For example mate-polkit tries to use newer ayatana implementation and falls back to old one if not found:
https://github.com/mate-desktop/mate-polkit/commit/65a6c367e28e338dc74931dece1af9e53338276f

**Comment by pacho2** [comment]
[1.patch.txt](https://github.com/mate-desktop/mate-control-center/files/11354867/1.patch.txt)

I ported it and it seems to work with 1.26.0

**Comment by pacho2** [comment]
[1.patch.txt](https://github.com/mate-desktop/mate-control-center/files/11471753/1.patch.txt)

This fixes the detection when library is present but its support is disabled and also remove some bashisms

**Comment by raveit65** [comment]
Pull request?

**Comment by rubyFeedback** [comment]
Is ayatana-indicator mandatory? I don't seem to be able to find a way to disable it during configure; not sure if mate-control-center depends on it internally or not. If it is not mandatory then perhaps a --disable-ayatana-indicator or so could be nice to have.
