### ISSUE TITLE
window-properties.ui labels need an accessible relation pointing to the group they label

### ISSUE THREAD

**Issue by joanmarie** [mate-desktop/mate-control-center#703]
Steps to reproduce:
1. Launch Orca and mate-window-properties
2. Tab among the widgets

Expected results: Orca would announce each new section of controls.

Actual results: Orca does not announce each new section of controls. Often the widget labels are sufficient to understand what the widget is for. But when you give focus to "Alt", all Orca says is "Alt". Orca doesn't say "Movement Key" or "To move a window, press-and-hold this key then grab the window".

The reason Orca doesn't announce the labels is that it has no idea what those labels are associated with. There are ATK relations which you can use to fix this.

Related aside: Orca does announce the "To move a window...." label text when the dialog first appears. That's because Orca is looking for long static text that might be helpful information that should be presented for newly-opened dialogs. Because this label doesn't have an accessible relation pointing to the radio  button group, and because it's sufficiently long, it passes Orca's heuristic. While I (Orca maintainer) can try to give Orca more smarts to eliminate that initial chattiness, it's not going to solve the problem that tabbing to the "Alt" radio button doesn't result in the user being told what choosing "Alt" will do. The accessible relation needs to be added. And once you add it, that initial chattiness will go away on its own.

cc @cwendling

**Comment by cwendling** [comment]
Thanks for the detailed explanations (esp. on Orca speaking the movement keys label that I wouldn't necessarily have picked up), should be all fixed by #704. If you have the opportunity, please give it a try :)
