### ISSUE TITLE
Touchpad scrolling behavior does not match checkbox selection in Mouse Preferences

### ISSUE THREAD

**Issue by mesov** [mate-desktop/mate-control-center#709]
#### Expected behaviour

All scrolling options can be checked or unchecked, and are made available or unavailable accordingly.

OR

Mutually exclusive options get their checkbox greyed out if the other one is checked, or radio buttons are used instead of checkboxes (as in this mockup of Mouse Preference: https://github.com/mate-desktop/mate-control-center/issues/228).

#### Actual behaviour

All scrolling options can be checked or unchecked, but some behave as if mutually exclusive. There is no indication that some of the checked options are not going to be available.

#### Steps to reproduce the behaviour

In Mouse Preferences, Touchpad tab, Scrolling section, check all four scrolling option combinations (vertical and horizontal edge scrolling, vertical and horizontal two-finger scrolling). Two-finger scrolling works, edge scrolling does not work.

Uncheck all but two-finger horizontal edge scrolling and vertical edge scrolling. The latter is working but not the former.

#### MATE general version

1.26

#### Package version

mate-control-center 1.26.0-2

#### Linux Distribution

Trisquel 11

#### Link to bugreport of your Distribution (requirement)

https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/93

#### Related commits

"Touchpad settings: Support edge and two-finger scrolling independently" https://github.com/mate-desktop/mate-control-center/pull/229.

**Comment by mesov** [comment]
On my current system, horizontal edge scrolling is not working at all, but this would need to be tested as a possible hardware related problem.

All the other software based incompatibilities mentioned above remain: two-finger vertical scrolling blocks vertical edge scrolling, and two-finger horizontal scrolling only works if two-finger vertical scrolling is selected.

**Comment by lukefromdc** [comment]
You should probably open a bug report against xserver-xorg-input-libinput for this

**Comment by mesov** [comment]
Right. It seems to have been discussed some time ago: https://gitlab.freedesktop.org/libinput/libinput/-/issues/590.

I may add a comment there in case someone wants to take this up.
