### ISSUE TITLE
`mate-appearance-properties` loads a CPU core to 100%

### ISSUE THREAD

**Issue by flexiondotorg** [mate-desktop/mate-control-center#71]
Hi,

When I start I start `System -> Preferences -> Appearance` I see that many of the themes don't have thumbnails and show a question mark icon instead.

As a result, `mate-appearance-properties` tries to generate the required thumbnails. This activity loads a single CPU core to 100% and never completes. Upon closing `mate-appearance-properties` the window is closed but the process continues to run, indefinitely in the background, occupying 100% of a CPU.

If I kill the process then CPU load returns to normal, but the next time `mate-appearance-properties` is executed a CPU core is fully utilised again.

Regards, Martin.
##

**Comment by RichardNeill** [comment]
For what it's worth, I also just saw this. Deleting the file fixes it:  
As these files are generated by KDE... it really would be worth fixing the issue if possible - even with a workaround to simply ignore the file.

--- begin ---
cat ~/.local/share/Trash/files/.gtkrc-2.0 
# This file was written by KDE
# You can edit it in the KDE control center, under "GTK Styles and Fonts"

include "/usr/share/themes/Clearlooks/gtk-2.0/gtkrc"
include "/etc/gtk-2.0/gtkrc"

style "user-font"
{
        font_name="Tahoma"
}
widget_class "*" style "user-font"

gtk-theme-name="Clearlooks"
gtk-font-name="Tahoma 9"
---- end ---

**Comment by monsta** [comment]
Ok, I can also confirm the mentioned config file causes 100% CPU load.

**Comment by lyssdod** [comment]
Same thing here. MATE 1.10.2

**Comment by lyssdod** [comment]
http://forums.mate-desktop.org/viewtopic.php?f=2&t=1674 here it's advised to simply delete all .gtkrc* files

**Comment by pirate486743186** [comment]
lol, i had the same thing.... in 2017....
I suspect that was the cause for some glitches in Firefox and Seamonkey. I'll see if they reappear....

Isn't this actually a GTK bug?

**Comment by monsta** [comment]
Not sure, but might be GTK+ bug, yes. Were there any upstream reports on that?

**Comment by monsta** [comment]
Or maybe not. We have some old gtkrc parsing code here...

**Comment by flexiondotorg** [comment]
I can no longer reproduce this bug using MATE 1.22, 1.24 or 1.26. I will close this.
