### ISSUE TITLE
 [Feature request] mate-display-properties: A command line option to generate a default ~/.config/monitors.xml

### ISSUE THREAD

**Issue by davidhedlund** [mate-desktop/mate-control-center#711]
#### Expected behaviour
* There is no command to generate a default "$HOME/.config/monitors.xml". A script cannot be written that manages mate-display-properties (the Apply button is not pre-selected for example).

* Solution: `mate-display-properties --make-monitors.xml` to generate a default "$HOME/.config/monitors.xml" file. The screen resolution can then be modified (regardless of the values) via Bash:

```
variable_name="width"; variable_value="1920"; sed -i "s/$variable_name.*$variable_name/$variable_name>$variable_value<\/$variable_name/g" "$HOME/.config/monitors.xml"
variable_name="height"; variable_value="1080"; sed -i "s/$variable_name.*$variable_name/$variable_name>$variable_value<\/$variable_name/g" "$HOME/.config/monitors.xml"
```

##### Notes
xrandr will temporarily change the screen resolution with: `screen_resolution="1920x1080"; xrandr --output "$(xrandr --listactivemonitors | tail -1 | awk '{ print $NF }')" --mode "$screen_resolution"` Also, it to ~/.bashrc to make it permanently will interfere with "$HOME/.config/monitors.xml" that is generated by mate-display-properties

#### Actual behaviour
"$HOME/.config/monitors.xml" is generated

#### Steps to reproduce the behaviour
* Run mate-display-properties. Click on the Apply button

#### MATE general version
1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu MATE 22.04

#### Link to bugreport of your Distribution (requirement)
Not applicable as this is a feature request.

**Comment by davidhedlund** [comment]
* https://github.com/mate-desktop/mate-control-center/issues/710

**Comment by GrahamxReed** [comment]
Being able to fully automate a script to set up an ergonomic working environment seems like a no-brainer.

**Comment by raveit65** [comment]
No need to open 2 reports, closing this one.

**Comment by davidhedlund** [comment]
> No need to open 2 reports, closing this one.

Sorry, these are two completely different issues as I rewrote the first one.

**Comment by davidhedlund** [comment]
This issue is to _set_ the data, while https://github.com/mate-desktop/mate-control-center/issues/710 is used to get the data.

**Comment by davidhedlund** [comment]
I merged this issue to a new "Set data in monitors.xml" section in https://github.com/mate-desktop/mate-control-center/issues/710
