### ISSUE TITLE
How can I set the default browser to Chrome?

### ISSUE THREAD

**Issue by MartinThoma** [mate-desktop/mate-control-center#91]
Currently, when I click on a link in a PDF document opened in `atril` (MATE Document Viewer 1.6.1) it opens Firefox. The same happens when I click in Sublime Text 3 on "Purchase License".

This is my current configuration:

```
/etc/alternatives/gnome-www-browser -> /usr/bin/google-chrome-stable
/etc/alternatives/x-www-browser -> /usr/bin/google-chrome-stable
```

When I start `mate-default-applications-properties` there is only Firefox.

I've just edited `/usr/share/applications/defaults.list` so that there is no Firefox entry. (I've replaced every Firefox entry by a chrome entry and restarted my system.) And still new websites are opened with Firefox.

`sudo update-alternatives --config x-www-browser` is also already set to Chrome.

**Comment by twoface639** [comment]
going to system preference and selecting chrome woks on ubuntu MATE 15.04

**Comment by ssrublev** [comment]
Thanks for the solution! I had the same issue, but I wanted to engage Yandex-browser instead of Chrome (on Fedora). I had to remove "yandex-browser-beta.desktop" file and there was also "userapp-yandex-browser-beta-0N6R2X.desktop" file in "~/.local/share/applications/".
